// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmLidarLuxObject.h"

static int __ZcmLidarLuxObject_hash_computed;
static uint64_t __ZcmLidarLuxObject_hash;

uint64_t __ZcmLidarLuxObject_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmLidarLuxObject_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmLidarLuxObject_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x23d1188e545f0b8dLL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __ZcmLidarLux2DPoint_hash_recursive(&cp)
         + __ZcmLidarLux2DPoint_hash_recursive(&cp)
         + __ZcmLidarLux2DPoint_hash_recursive(&cp)
         + __ZcmLidarLux2DPoint_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __ZcmLidarLux2DPoint_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __ZcmLidarLux2DPoint_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __ZcmLidarLux2DPoint_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __ZcmLidarLux2DPoint_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmLidarLuxObject_get_hash(void)
{
    if (!__ZcmLidarLuxObject_hash_computed) {
        __ZcmLidarLuxObject_hash = (int64_t)__ZcmLidarLuxObject_hash_recursive(NULL);
        __ZcmLidarLuxObject_hash_computed = 1;
    }

    return __ZcmLidarLuxObject_hash;
}

int __ZcmLidarLuxObject_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmLidarLuxObject* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectId), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].age), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].predictionAge), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].relativeTimestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_encode_array(buf, offset + pos, maxlen - pos, &(p[element].refPoint), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_encode_array(buf, offset + pos, maxlen - pos, &(p[element].refPointSigma), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_encode_array(buf, offset + pos, maxlen - pos, &(p[element].closestPoint), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_encode_array(buf, offset + pos, maxlen - pos, &(p[element].boundingBoxCenter), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].boundingBoxWidth), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].boundingBoxLength), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxCenter), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxOrientation), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_encode_array(buf, offset + pos, maxlen - pos, &(p[element].absVelocity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].absVelSigmaX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].absVelSigmaY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_encode_array(buf, offset + pos, maxlen - pos, &(p[element].relVelocity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectClass), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].classAge), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].classCertainty), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].numContourPoints), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].numContourPointsIsValid), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_encode_array(buf, offset + pos, maxlen - pos, p[element].contourPoints, p[element].numContourPoints);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmLidarLuxObject_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmLidarLuxObject* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmLidarLuxObject_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmLidarLuxObject_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmLidarLuxObject_encoded_array_size(const ZcmLidarLuxObject* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __int64_t_encoded_array_size(&(p[element].objectId), 1);

        size += __int32_t_encoded_array_size(&(p[element].age), 1);

        size += __int32_t_encoded_array_size(&(p[element].predictionAge), 1);

        size += __int32_t_encoded_array_size(&(p[element].relativeTimestamp), 1);

        size += __ZcmLidarLux2DPoint_encoded_array_size(&(p[element].refPoint), 1);

        size += __ZcmLidarLux2DPoint_encoded_array_size(&(p[element].refPointSigma), 1);

        size += __ZcmLidarLux2DPoint_encoded_array_size(&(p[element].closestPoint), 1);

        size += __ZcmLidarLux2DPoint_encoded_array_size(&(p[element].boundingBoxCenter), 1);

        size += __int32_t_encoded_array_size(&(p[element].boundingBoxWidth), 1);

        size += __int32_t_encoded_array_size(&(p[element].boundingBoxLength), 1);

        size += __ZcmLidarLux2DPoint_encoded_array_size(&(p[element].objectBoxCenter), 1);

        size += __int32_t_encoded_array_size(&(p[element].objectBoxSizeX), 1);

        size += __int32_t_encoded_array_size(&(p[element].objectBoxSizeY), 1);

        size += __int16_t_encoded_array_size(&(p[element].objectBoxOrientation), 1);

        size += __ZcmLidarLux2DPoint_encoded_array_size(&(p[element].absVelocity), 1);

        size += __int32_t_encoded_array_size(&(p[element].absVelSigmaX), 1);

        size += __int32_t_encoded_array_size(&(p[element].absVelSigmaY), 1);

        size += __ZcmLidarLux2DPoint_encoded_array_size(&(p[element].relVelocity), 1);

        size += __int8_t_encoded_array_size(&(p[element].objectClass), 1);

        size += __int32_t_encoded_array_size(&(p[element].classAge), 1);

        size += __int32_t_encoded_array_size(&(p[element].classCertainty), 1);

        size += __int32_t_encoded_array_size(&(p[element].numContourPoints), 1);

        size += __boolean_encoded_array_size(&(p[element].numContourPointsIsValid), 1);

        size += __ZcmLidarLux2DPoint_encoded_array_size(p[element].contourPoints, p[element].numContourPoints);

    }
    return size;
}

uint32_t ZcmLidarLuxObject_encoded_size(const ZcmLidarLuxObject* p)
{
    return 8 + __ZcmLidarLuxObject_encoded_array_size(p, 1);
}

uint32_t ZcmLidarLuxObject_struct_size(void)
{
    return sizeof(ZcmLidarLuxObject);
}

uint32_t ZcmLidarLuxObject_num_fields(void)
{
    return 24;
}

int ZcmLidarLuxObject_get_field(const ZcmLidarLuxObject* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmLidarLuxObject_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "objectId";
            f->type = ZCM_FIELD_INT64_T;
            f->typestr = "int64_t";
            f->num_dim = 0;
            f->data = (void*) &p->objectId;
            return 0;
        }
        
        case 1: {
            f->name = "age";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->age;
            return 0;
        }
        
        case 2: {
            f->name = "predictionAge";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->predictionAge;
            return 0;
        }
        
        case 3: {
            f->name = "relativeTimestamp";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->relativeTimestamp;
            return 0;
        }
        
        case 4: {
            /* ZcmLidarLux2DPoint */
            f->name = "refPoint";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmLidarLux2DPoint";
            f->num_dim = 0;
            f->data = (void*) &p->refPoint;
            return 0;
        }
        
        case 5: {
            /* ZcmLidarLux2DPoint */
            f->name = "refPointSigma";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmLidarLux2DPoint";
            f->num_dim = 0;
            f->data = (void*) &p->refPointSigma;
            return 0;
        }
        
        case 6: {
            /* ZcmLidarLux2DPoint */
            f->name = "closestPoint";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmLidarLux2DPoint";
            f->num_dim = 0;
            f->data = (void*) &p->closestPoint;
            return 0;
        }
        
        case 7: {
            /* ZcmLidarLux2DPoint */
            f->name = "boundingBoxCenter";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmLidarLux2DPoint";
            f->num_dim = 0;
            f->data = (void*) &p->boundingBoxCenter;
            return 0;
        }
        
        case 8: {
            f->name = "boundingBoxWidth";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->boundingBoxWidth;
            return 0;
        }
        
        case 9: {
            f->name = "boundingBoxLength";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->boundingBoxLength;
            return 0;
        }
        
        case 10: {
            /* ZcmLidarLux2DPoint */
            f->name = "objectBoxCenter";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmLidarLux2DPoint";
            f->num_dim = 0;
            f->data = (void*) &p->objectBoxCenter;
            return 0;
        }
        
        case 11: {
            f->name = "objectBoxSizeX";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->objectBoxSizeX;
            return 0;
        }
        
        case 12: {
            f->name = "objectBoxSizeY";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->objectBoxSizeY;
            return 0;
        }
        
        case 13: {
            f->name = "objectBoxOrientation";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->objectBoxOrientation;
            return 0;
        }
        
        case 14: {
            /* ZcmLidarLux2DPoint */
            f->name = "absVelocity";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmLidarLux2DPoint";
            f->num_dim = 0;
            f->data = (void*) &p->absVelocity;
            return 0;
        }
        
        case 15: {
            f->name = "absVelSigmaX";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->absVelSigmaX;
            return 0;
        }
        
        case 16: {
            f->name = "absVelSigmaY";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->absVelSigmaY;
            return 0;
        }
        
        case 17: {
            /* ZcmLidarLux2DPoint */
            f->name = "relVelocity";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmLidarLux2DPoint";
            f->num_dim = 0;
            f->data = (void*) &p->relVelocity;
            return 0;
        }
        
        case 18: {
            f->name = "objectClass";
            f->type = ZCM_FIELD_INT8_T;
            f->typestr = "int8_t";
            f->num_dim = 0;
            f->data = (void*) &p->objectClass;
            return 0;
        }
        
        case 19: {
            f->name = "classAge";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->classAge;
            return 0;
        }
        
        case 20: {
            f->name = "classCertainty";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->classCertainty;
            return 0;
        }
        
        case 21: {
            f->name = "numContourPoints";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->numContourPoints;
            return 0;
        }
        
        case 22: {
            f->name = "numContourPointsIsValid";
            f->type = ZCM_FIELD_BOOLEAN;
            f->typestr = "boolean";
            f->num_dim = 0;
            f->data = (void*) &p->numContourPointsIsValid;
            return 0;
        }
        
        case 23: {
            /* ZcmLidarLux2DPoint */
            f->name = "contourPoints";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmLidarLux2DPoint";
            f->num_dim = 1;
            f->dim_size[0] = p->numContourPoints;
            f->dim_is_variable[0] = 1;
            f->data = (void*) &p->contourPoints;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmLidarLuxObject_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmLidarLuxObject_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmLidarLuxObject_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmLidarLuxObject_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmLidarLuxObject_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmLidarLuxObject_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmLidarLuxObject_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmLidarLuxObject_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmLidarLuxObject_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmLidarLuxObject_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmLidarLuxObject* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectId), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].age), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].predictionAge), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].relativeTimestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_decode_array(buf, offset + pos, maxlen - pos, &(p[element].refPoint), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_decode_array(buf, offset + pos, maxlen - pos, &(p[element].refPointSigma), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_decode_array(buf, offset + pos, maxlen - pos, &(p[element].closestPoint), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_decode_array(buf, offset + pos, maxlen - pos, &(p[element].boundingBoxCenter), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].boundingBoxWidth), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].boundingBoxLength), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxCenter), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxOrientation), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_decode_array(buf, offset + pos, maxlen - pos, &(p[element].absVelocity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].absVelSigmaX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].absVelSigmaY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarLux2DPoint_decode_array(buf, offset + pos, maxlen - pos, &(p[element].relVelocity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectClass), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].classAge), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].classCertainty), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].numContourPoints), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].numContourPointsIsValid), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].contourPoints = (ZcmLidarLux2DPoint*) zcm_malloc(sizeof(ZcmLidarLux2DPoint) * p[element].numContourPoints);
        thislen = __ZcmLidarLux2DPoint_decode_array(buf, offset + pos, maxlen - pos, p[element].contourPoints, p[element].numContourPoints);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmLidarLuxObject_decode_array_cleanup(ZcmLidarLuxObject* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __int64_t_decode_array_cleanup(&(p[element].objectId), 1);

        __int32_t_decode_array_cleanup(&(p[element].age), 1);

        __int32_t_decode_array_cleanup(&(p[element].predictionAge), 1);

        __int32_t_decode_array_cleanup(&(p[element].relativeTimestamp), 1);

        __ZcmLidarLux2DPoint_decode_array_cleanup(&(p[element].refPoint), 1);

        __ZcmLidarLux2DPoint_decode_array_cleanup(&(p[element].refPointSigma), 1);

        __ZcmLidarLux2DPoint_decode_array_cleanup(&(p[element].closestPoint), 1);

        __ZcmLidarLux2DPoint_decode_array_cleanup(&(p[element].boundingBoxCenter), 1);

        __int32_t_decode_array_cleanup(&(p[element].boundingBoxWidth), 1);

        __int32_t_decode_array_cleanup(&(p[element].boundingBoxLength), 1);

        __ZcmLidarLux2DPoint_decode_array_cleanup(&(p[element].objectBoxCenter), 1);

        __int32_t_decode_array_cleanup(&(p[element].objectBoxSizeX), 1);

        __int32_t_decode_array_cleanup(&(p[element].objectBoxSizeY), 1);

        __int16_t_decode_array_cleanup(&(p[element].objectBoxOrientation), 1);

        __ZcmLidarLux2DPoint_decode_array_cleanup(&(p[element].absVelocity), 1);

        __int32_t_decode_array_cleanup(&(p[element].absVelSigmaX), 1);

        __int32_t_decode_array_cleanup(&(p[element].absVelSigmaY), 1);

        __ZcmLidarLux2DPoint_decode_array_cleanup(&(p[element].relVelocity), 1);

        __int8_t_decode_array_cleanup(&(p[element].objectClass), 1);

        __int32_t_decode_array_cleanup(&(p[element].classAge), 1);

        __int32_t_decode_array_cleanup(&(p[element].classCertainty), 1);

        __int32_t_decode_array_cleanup(&(p[element].numContourPoints), 1);

        __boolean_decode_array_cleanup(&(p[element].numContourPointsIsValid), 1);

        __ZcmLidarLux2DPoint_decode_array_cleanup(p[element].contourPoints, p[element].numContourPoints);
        if (p[element].contourPoints) free(p[element].contourPoints);

    }
    return 0;
}

int ZcmLidarLuxObject_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmLidarLuxObject* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmLidarLuxObject_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmLidarLuxObject_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmLidarLuxObject_decode_cleanup(ZcmLidarLuxObject* p)
{
    return __ZcmLidarLuxObject_decode_array_cleanup(p, 1);
}

uint32_t __ZcmLidarLuxObject_clone_array(const ZcmLidarLuxObject* p, ZcmLidarLuxObject* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __int64_t_clone_array(&(p[element].objectId), &(q[element].objectId), 1);

        n += __int32_t_clone_array(&(p[element].age), &(q[element].age), 1);

        n += __int32_t_clone_array(&(p[element].predictionAge), &(q[element].predictionAge), 1);

        n += __int32_t_clone_array(&(p[element].relativeTimestamp), &(q[element].relativeTimestamp), 1);

        n += __ZcmLidarLux2DPoint_clone_array(&(p[element].refPoint), &(q[element].refPoint), 1);

        n += __ZcmLidarLux2DPoint_clone_array(&(p[element].refPointSigma), &(q[element].refPointSigma), 1);

        n += __ZcmLidarLux2DPoint_clone_array(&(p[element].closestPoint), &(q[element].closestPoint), 1);

        n += __ZcmLidarLux2DPoint_clone_array(&(p[element].boundingBoxCenter), &(q[element].boundingBoxCenter), 1);

        n += __int32_t_clone_array(&(p[element].boundingBoxWidth), &(q[element].boundingBoxWidth), 1);

        n += __int32_t_clone_array(&(p[element].boundingBoxLength), &(q[element].boundingBoxLength), 1);

        n += __ZcmLidarLux2DPoint_clone_array(&(p[element].objectBoxCenter), &(q[element].objectBoxCenter), 1);

        n += __int32_t_clone_array(&(p[element].objectBoxSizeX), &(q[element].objectBoxSizeX), 1);

        n += __int32_t_clone_array(&(p[element].objectBoxSizeY), &(q[element].objectBoxSizeY), 1);

        n += __int16_t_clone_array(&(p[element].objectBoxOrientation), &(q[element].objectBoxOrientation), 1);

        n += __ZcmLidarLux2DPoint_clone_array(&(p[element].absVelocity), &(q[element].absVelocity), 1);

        n += __int32_t_clone_array(&(p[element].absVelSigmaX), &(q[element].absVelSigmaX), 1);

        n += __int32_t_clone_array(&(p[element].absVelSigmaY), &(q[element].absVelSigmaY), 1);

        n += __ZcmLidarLux2DPoint_clone_array(&(p[element].relVelocity), &(q[element].relVelocity), 1);

        n += __int8_t_clone_array(&(p[element].objectClass), &(q[element].objectClass), 1);

        n += __int32_t_clone_array(&(p[element].classAge), &(q[element].classAge), 1);

        n += __int32_t_clone_array(&(p[element].classCertainty), &(q[element].classCertainty), 1);

        n += __int32_t_clone_array(&(p[element].numContourPoints), &(q[element].numContourPoints), 1);

        n += __boolean_clone_array(&(p[element].numContourPointsIsValid), &(q[element].numContourPointsIsValid), 1);

        q[element].contourPoints = (ZcmLidarLux2DPoint*) zcm_malloc(sizeof(ZcmLidarLux2DPoint) * q[element].numContourPoints);
        n += __ZcmLidarLux2DPoint_clone_array(p[element].contourPoints, q[element].contourPoints, p[element].numContourPoints);

    }
    return n;
}

ZcmLidarLuxObject* ZcmLidarLuxObject_copy(const ZcmLidarLuxObject* p)
{
    ZcmLidarLuxObject* q = (ZcmLidarLuxObject*) malloc(sizeof(ZcmLidarLuxObject));
    __ZcmLidarLuxObject_clone_array(p, q, 1);
    return q;
}

void ZcmLidarLuxObject_destroy(ZcmLidarLuxObject* p)
{
    __ZcmLidarLuxObject_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmLidarLuxObject_publish(zcm_t* zcm, const char* channel, const ZcmLidarLuxObject* p)
{
      uint32_t max_data_size = ZcmLidarLuxObject_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmLidarLuxObject_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmLidarLuxObject_subscription_t {
    ZcmLidarLuxObject_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmLidarLuxObject_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmLidarLuxObject p;
    memset(&p, 0, sizeof(ZcmLidarLuxObject));
    status = ZcmLidarLuxObject_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmLidarLuxObject!!!\n", status);
        return;
    }

    ZcmLidarLuxObject_subscription_t* h = (ZcmLidarLuxObject_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmLidarLuxObject_decode_cleanup (&p);
}

ZcmLidarLuxObject_subscription_t* ZcmLidarLuxObject_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmLidarLuxObject_handler_t f, void* userdata)
{
    ZcmLidarLuxObject_subscription_t* n = (ZcmLidarLuxObject_subscription_t*)
                       malloc(sizeof(ZcmLidarLuxObject_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmLidarLuxObject_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmLidarLuxObject ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmLidarLuxObject_unsubscribe(zcm_t* zcm, ZcmLidarLuxObject_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmLidarLuxObject_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

