// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmLidarLuxPoint.h"

static int __ZcmLidarLuxPoint_hash_computed;
static uint64_t __ZcmLidarLuxPoint_hash;

uint64_t __ZcmLidarLuxPoint_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmLidarLuxPoint_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmLidarLuxPoint_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x493f18b3d477330cLL
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmLidarLuxPoint_get_hash(void)
{
    if (!__ZcmLidarLuxPoint_hash_computed) {
        __ZcmLidarLuxPoint_hash = (int64_t)__ZcmLidarLuxPoint_hash_recursive(NULL);
        __ZcmLidarLuxPoint_hash_computed = 1;
    }

    return __ZcmLidarLuxPoint_hash;
}

int __ZcmLidarLuxPoint_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmLidarLuxPoint* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].echoId), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].layerId), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].flags), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].horizontalAngle), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].radialDistance), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].echoPulseWidth), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmLidarLuxPoint_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmLidarLuxPoint* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmLidarLuxPoint_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmLidarLuxPoint_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmLidarLuxPoint_encoded_array_size(const ZcmLidarLuxPoint* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __int16_t_encoded_array_size(&(p[element].echoId), 1);

        size += __int16_t_encoded_array_size(&(p[element].layerId), 1);

        size += __int32_t_encoded_array_size(&(p[element].flags), 1);

        size += __int32_t_encoded_array_size(&(p[element].horizontalAngle), 1);

        size += __float_encoded_array_size(&(p[element].radialDistance), 1);

        size += __float_encoded_array_size(&(p[element].x), 1);

        size += __float_encoded_array_size(&(p[element].y), 1);

        size += __float_encoded_array_size(&(p[element].z), 1);

        size += __float_encoded_array_size(&(p[element].echoPulseWidth), 1);

    }
    return size;
}

uint32_t ZcmLidarLuxPoint_encoded_size(const ZcmLidarLuxPoint* p)
{
    return 8 + __ZcmLidarLuxPoint_encoded_array_size(p, 1);
}

uint32_t ZcmLidarLuxPoint_struct_size(void)
{
    return sizeof(ZcmLidarLuxPoint);
}

uint32_t ZcmLidarLuxPoint_num_fields(void)
{
    return 9;
}

int ZcmLidarLuxPoint_get_field(const ZcmLidarLuxPoint* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmLidarLuxPoint_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "echoId";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->echoId;
            return 0;
        }
        
        case 1: {
            f->name = "layerId";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->layerId;
            return 0;
        }
        
        case 2: {
            f->name = "flags";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->flags;
            return 0;
        }
        
        case 3: {
            f->name = "horizontalAngle";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->horizontalAngle;
            return 0;
        }
        
        case 4: {
            f->name = "radialDistance";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->radialDistance;
            return 0;
        }
        
        case 5: {
            f->name = "x";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->x;
            return 0;
        }
        
        case 6: {
            f->name = "y";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->y;
            return 0;
        }
        
        case 7: {
            f->name = "z";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->z;
            return 0;
        }
        
        case 8: {
            f->name = "echoPulseWidth";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->echoPulseWidth;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmLidarLuxPoint_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmLidarLuxPoint_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmLidarLuxPoint_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmLidarLuxPoint_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmLidarLuxPoint_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmLidarLuxPoint_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmLidarLuxPoint_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmLidarLuxPoint_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmLidarLuxPoint_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmLidarLuxPoint_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmLidarLuxPoint* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].echoId), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].layerId), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].flags), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].horizontalAngle), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].radialDistance), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].echoPulseWidth), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmLidarLuxPoint_decode_array_cleanup(ZcmLidarLuxPoint* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __int16_t_decode_array_cleanup(&(p[element].echoId), 1);

        __int16_t_decode_array_cleanup(&(p[element].layerId), 1);

        __int32_t_decode_array_cleanup(&(p[element].flags), 1);

        __int32_t_decode_array_cleanup(&(p[element].horizontalAngle), 1);

        __float_decode_array_cleanup(&(p[element].radialDistance), 1);

        __float_decode_array_cleanup(&(p[element].x), 1);

        __float_decode_array_cleanup(&(p[element].y), 1);

        __float_decode_array_cleanup(&(p[element].z), 1);

        __float_decode_array_cleanup(&(p[element].echoPulseWidth), 1);

    }
    return 0;
}

int ZcmLidarLuxPoint_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmLidarLuxPoint* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmLidarLuxPoint_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmLidarLuxPoint_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmLidarLuxPoint_decode_cleanup(ZcmLidarLuxPoint* p)
{
    return __ZcmLidarLuxPoint_decode_array_cleanup(p, 1);
}

uint32_t __ZcmLidarLuxPoint_clone_array(const ZcmLidarLuxPoint* p, ZcmLidarLuxPoint* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __int16_t_clone_array(&(p[element].echoId), &(q[element].echoId), 1);

        n += __int16_t_clone_array(&(p[element].layerId), &(q[element].layerId), 1);

        n += __int32_t_clone_array(&(p[element].flags), &(q[element].flags), 1);

        n += __int32_t_clone_array(&(p[element].horizontalAngle), &(q[element].horizontalAngle), 1);

        n += __float_clone_array(&(p[element].radialDistance), &(q[element].radialDistance), 1);

        n += __float_clone_array(&(p[element].x), &(q[element].x), 1);

        n += __float_clone_array(&(p[element].y), &(q[element].y), 1);

        n += __float_clone_array(&(p[element].z), &(q[element].z), 1);

        n += __float_clone_array(&(p[element].echoPulseWidth), &(q[element].echoPulseWidth), 1);

    }
    return n;
}

ZcmLidarLuxPoint* ZcmLidarLuxPoint_copy(const ZcmLidarLuxPoint* p)
{
    ZcmLidarLuxPoint* q = (ZcmLidarLuxPoint*) malloc(sizeof(ZcmLidarLuxPoint));
    __ZcmLidarLuxPoint_clone_array(p, q, 1);
    return q;
}

void ZcmLidarLuxPoint_destroy(ZcmLidarLuxPoint* p)
{
    __ZcmLidarLuxPoint_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmLidarLuxPoint_publish(zcm_t* zcm, const char* channel, const ZcmLidarLuxPoint* p)
{
      uint32_t max_data_size = ZcmLidarLuxPoint_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmLidarLuxPoint_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmLidarLuxPoint_subscription_t {
    ZcmLidarLuxPoint_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmLidarLuxPoint_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmLidarLuxPoint p;
    memset(&p, 0, sizeof(ZcmLidarLuxPoint));
    status = ZcmLidarLuxPoint_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmLidarLuxPoint!!!\n", status);
        return;
    }

    ZcmLidarLuxPoint_subscription_t* h = (ZcmLidarLuxPoint_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmLidarLuxPoint_decode_cleanup (&p);
}

ZcmLidarLuxPoint_subscription_t* ZcmLidarLuxPoint_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmLidarLuxPoint_handler_t f, void* userdata)
{
    ZcmLidarLuxPoint_subscription_t* n = (ZcmLidarLuxPoint_subscription_t*)
                       malloc(sizeof(ZcmLidarLuxPoint_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmLidarLuxPoint_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmLidarLuxPoint ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmLidarLuxPoint_unsubscribe(zcm_t* zcm, ZcmLidarLuxPoint_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmLidarLuxPoint_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

