// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmCamWDRaindropPoint.h"

static int __ZcmCamWDRaindropPoint_hash_computed;
static uint64_t __ZcmCamWDRaindropPoint_hash;

uint64_t __ZcmCamWDRaindropPoint_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmCamWDRaindropPoint_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmCamWDRaindropPoint_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xa2b19692eaf05a2dLL
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmCamWDRaindropPoint_get_hash(void)
{
    if (!__ZcmCamWDRaindropPoint_hash_computed) {
        __ZcmCamWDRaindropPoint_hash = (int64_t)__ZcmCamWDRaindropPoint_hash_recursive(NULL);
        __ZcmCamWDRaindropPoint_hash_computed = 1;
    }

    return __ZcmCamWDRaindropPoint_hash;
}

int __ZcmCamWDRaindropPoint_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCamWDRaindropPoint* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].radius), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].area), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].blur_rate), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmCamWDRaindropPoint_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCamWDRaindropPoint* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmCamWDRaindropPoint_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmCamWDRaindropPoint_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmCamWDRaindropPoint_encoded_array_size(const ZcmCamWDRaindropPoint* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __int32_t_encoded_array_size(&(p[element].x), 1);

        size += __int32_t_encoded_array_size(&(p[element].y), 1);

        size += __int32_t_encoded_array_size(&(p[element].radius), 1);

        size += __int32_t_encoded_array_size(&(p[element].area), 1);

        size += __int8_t_encoded_array_size(&(p[element].blur_rate), 1);

    }
    return size;
}

uint32_t ZcmCamWDRaindropPoint_encoded_size(const ZcmCamWDRaindropPoint* p)
{
    return 8 + __ZcmCamWDRaindropPoint_encoded_array_size(p, 1);
}

uint32_t ZcmCamWDRaindropPoint_struct_size(void)
{
    return sizeof(ZcmCamWDRaindropPoint);
}

uint32_t ZcmCamWDRaindropPoint_num_fields(void)
{
    return 5;
}

int ZcmCamWDRaindropPoint_get_field(const ZcmCamWDRaindropPoint* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmCamWDRaindropPoint_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "x";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->x;
            return 0;
        }
        
        case 1: {
            f->name = "y";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->y;
            return 0;
        }
        
        case 2: {
            f->name = "radius";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->radius;
            return 0;
        }
        
        case 3: {
            f->name = "area";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->area;
            return 0;
        }
        
        case 4: {
            f->name = "blur_rate";
            f->type = ZCM_FIELD_INT8_T;
            f->typestr = "int8_t";
            f->num_dim = 0;
            f->data = (void*) &p->blur_rate;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmCamWDRaindropPoint_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmCamWDRaindropPoint_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmCamWDRaindropPoint_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmCamWDRaindropPoint_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmCamWDRaindropPoint_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmCamWDRaindropPoint_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmCamWDRaindropPoint_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmCamWDRaindropPoint_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmCamWDRaindropPoint_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmCamWDRaindropPoint_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCamWDRaindropPoint* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].radius), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].area), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].blur_rate), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmCamWDRaindropPoint_decode_array_cleanup(ZcmCamWDRaindropPoint* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __int32_t_decode_array_cleanup(&(p[element].x), 1);

        __int32_t_decode_array_cleanup(&(p[element].y), 1);

        __int32_t_decode_array_cleanup(&(p[element].radius), 1);

        __int32_t_decode_array_cleanup(&(p[element].area), 1);

        __int8_t_decode_array_cleanup(&(p[element].blur_rate), 1);

    }
    return 0;
}

int ZcmCamWDRaindropPoint_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCamWDRaindropPoint* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmCamWDRaindropPoint_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmCamWDRaindropPoint_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmCamWDRaindropPoint_decode_cleanup(ZcmCamWDRaindropPoint* p)
{
    return __ZcmCamWDRaindropPoint_decode_array_cleanup(p, 1);
}

uint32_t __ZcmCamWDRaindropPoint_clone_array(const ZcmCamWDRaindropPoint* p, ZcmCamWDRaindropPoint* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __int32_t_clone_array(&(p[element].x), &(q[element].x), 1);

        n += __int32_t_clone_array(&(p[element].y), &(q[element].y), 1);

        n += __int32_t_clone_array(&(p[element].radius), &(q[element].radius), 1);

        n += __int32_t_clone_array(&(p[element].area), &(q[element].area), 1);

        n += __int8_t_clone_array(&(p[element].blur_rate), &(q[element].blur_rate), 1);

    }
    return n;
}

ZcmCamWDRaindropPoint* ZcmCamWDRaindropPoint_copy(const ZcmCamWDRaindropPoint* p)
{
    ZcmCamWDRaindropPoint* q = (ZcmCamWDRaindropPoint*) malloc(sizeof(ZcmCamWDRaindropPoint));
    __ZcmCamWDRaindropPoint_clone_array(p, q, 1);
    return q;
}

void ZcmCamWDRaindropPoint_destroy(ZcmCamWDRaindropPoint* p)
{
    __ZcmCamWDRaindropPoint_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmCamWDRaindropPoint_publish(zcm_t* zcm, const char* channel, const ZcmCamWDRaindropPoint* p)
{
      uint32_t max_data_size = ZcmCamWDRaindropPoint_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmCamWDRaindropPoint_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmCamWDRaindropPoint_subscription_t {
    ZcmCamWDRaindropPoint_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmCamWDRaindropPoint_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmCamWDRaindropPoint p;
    memset(&p, 0, sizeof(ZcmCamWDRaindropPoint));
    status = ZcmCamWDRaindropPoint_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmCamWDRaindropPoint!!!\n", status);
        return;
    }

    ZcmCamWDRaindropPoint_subscription_t* h = (ZcmCamWDRaindropPoint_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmCamWDRaindropPoint_decode_cleanup (&p);
}

ZcmCamWDRaindropPoint_subscription_t* ZcmCamWDRaindropPoint_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmCamWDRaindropPoint_handler_t f, void* userdata)
{
    ZcmCamWDRaindropPoint_subscription_t* n = (ZcmCamWDRaindropPoint_subscription_t*)
                       malloc(sizeof(ZcmCamWDRaindropPoint_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmCamWDRaindropPoint_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmCamWDRaindropPoint ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmCamWDRaindropPoint_unsubscribe(zcm_t* zcm, ZcmCamWDRaindropPoint_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmCamWDRaindropPoint_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

