// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm/zcm_coretypes.h>
#include <zcm/zcm.h>

#ifndef _ZcmCamWDSnowground_h
#define _ZcmCamWDSnowground_h

#ifdef __cplusplus
extern "C" {
#endif

#include "ZcmService.h"
#define ZCMCAMWDSNOWGROUND_SNOWGROUND_GROUP_UNCHANGED 0
#define ZCMCAMWDSNOWGROUND_SNOWGROUND_GROUP_SNOWY 1
#define ZCMCAMWDSNOWGROUND_SNOWGROUND_GROUP_VSNOWY 2

/**
 * -------------------------------------------------------------------------------------
 * @struct ZcmCamWDSnowground
 * @brief Содержит информацию об обнаруженном снежном покрове на пути 
 * следования локомотива.
 * @var ZcmCamWDSnowground::group_info
 * @brief - Информация о распознавании: \n
 *          SNOWGROUND_GROUP_UNCHANGED - снег на земле отсутствует \n
 *          SNOWGROUND_GROUP_SNOWY - снежно \n
 *          SNOWGROUND_GROUP_VSNOWY - очень снежно. \n
 *
 */
typedef struct _ZcmCamWDSnowground ZcmCamWDSnowground;
struct _ZcmCamWDSnowground
{
    ZcmService service;
    int8_t     group_info;
};

/**
 * Create a deep copy of a ZcmCamWDSnowground.
 * When no longer needed, destroy it with ZcmCamWDSnowground_destroy()
 */
ZcmCamWDSnowground* ZcmCamWDSnowground_copy(const ZcmCamWDSnowground* to_copy);

/**
 * Destroy an instance of ZcmCamWDSnowground created by ZcmCamWDSnowground_copy()
 */
void ZcmCamWDSnowground_destroy(ZcmCamWDSnowground* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _ZcmCamWDSnowground_subscription_t ZcmCamWDSnowground_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * ZcmCamWDSnowground is received.
 */
typedef void(*ZcmCamWDSnowground_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const ZcmCamWDSnowground* msg, void* userdata);

/**
 * Publish a message of type ZcmCamWDSnowground using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int ZcmCamWDSnowground_publish(zcm_t* zcm, const char* channel, const ZcmCamWDSnowground* msg);

/**
 * Subscribe to messages of type ZcmCamWDSnowground using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to ZcmCamWDSnowground_unsubscribe.
 */
ZcmCamWDSnowground_subscription_t* ZcmCamWDSnowground_subscribe(zcm_t* zcm, const char* channel, ZcmCamWDSnowground_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by ZcmCamWDSnowground_subscribe()
 */
int ZcmCamWDSnowground_unsubscribe(zcm_t* zcm, ZcmCamWDSnowground_subscription_t* hid);
/**
 * Encode a message of type ZcmCamWDSnowground into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to ZcmCamWDSnowground_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int ZcmCamWDSnowground_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCamWDSnowground* p);

/**
 * Decode a message of type ZcmCamWDSnowground from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with ZcmCamWDSnowground_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int ZcmCamWDSnowground_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCamWDSnowground* msg);

/**
 * Release resources allocated by ZcmCamWDSnowground_decode()
 * @return 0
 */
int ZcmCamWDSnowground_decode_cleanup(ZcmCamWDSnowground* p);

/**
 * Check how many bytes are required to encode a message of type ZcmCamWDSnowground
 */
uint32_t ZcmCamWDSnowground_encoded_size(const ZcmCamWDSnowground* p);
uint32_t ZcmCamWDSnowground_struct_size(void);
uint32_t ZcmCamWDSnowground_num_fields(void);
int      ZcmCamWDSnowground_get_field(const ZcmCamWDSnowground* p, uint32_t i, zcm_field_t* f);
const zcm_type_info_t* ZcmCamWDSnowground_get_type_info(void);

// ZCM support functions. Users should not call these
int64_t  __ZcmCamWDSnowground_get_hash(void);
uint64_t __ZcmCamWDSnowground_hash_recursive(const __zcm_hash_ptr* p);
int      __ZcmCamWDSnowground_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmCamWDSnowground* p, uint32_t elements);
int      __ZcmCamWDSnowground_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmCamWDSnowground* p, uint32_t elements);
int      __ZcmCamWDSnowground_decode_array_cleanup(ZcmCamWDSnowground* p, uint32_t elements);
uint32_t __ZcmCamWDSnowground_encoded_array_size(const ZcmCamWDSnowground* p, uint32_t elements);
uint32_t __ZcmCamWDSnowground_clone_array(const ZcmCamWDSnowground* p, ZcmCamWDSnowground* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
