"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from ZcmCamWDSkylinePoint import ZcmCamWDSkylinePoint

from ZcmService import ZcmService

from ZcmCameraBaslerImagePresentation import ZcmCameraBaslerImagePresentation

class ZcmCamWDSkyline(object):
    __slots__ = ["service", "top_image", "bottom_image", "sky_average_line", "point_count", "sky_poly_line"]

    def __init__(self):
        self.service = ZcmService()
        self.top_image = ZcmCameraBaslerImagePresentation()
        self.bottom_image = ZcmCameraBaslerImagePresentation()
        self.sky_average_line = [ ZcmCamWDSkylinePoint() for dim0 in range(2) ]
        self.point_count = 0
        self.sky_poly_line = []

    def encode(self):
        buf = BytesIO()
        buf.write(ZcmCamWDSkyline._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.service._get_packed_fingerprint() == ZcmService._get_packed_fingerprint()
        self.service._encode_one(buf)
        assert self.top_image._get_packed_fingerprint() == ZcmCameraBaslerImagePresentation._get_packed_fingerprint()
        self.top_image._encode_one(buf)
        assert self.bottom_image._get_packed_fingerprint() == ZcmCameraBaslerImagePresentation._get_packed_fingerprint()
        self.bottom_image._encode_one(buf)
        for i0 in range(2):
            assert self.sky_average_line[i0]._get_packed_fingerprint() == ZcmCamWDSkylinePoint._get_packed_fingerprint()
            self.sky_average_line[i0]._encode_one(buf)
        buf.write(struct.pack(">i", self.point_count))
        for i0 in range(self.point_count):
            assert self.sky_poly_line[i0]._get_packed_fingerprint() == ZcmCamWDSkylinePoint._get_packed_fingerprint()
            self.sky_poly_line[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ZcmCamWDSkyline._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ZcmCamWDSkyline._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ZcmCamWDSkyline()
        self.service = ZcmService._decode_one(buf)
        self.top_image = ZcmCameraBaslerImagePresentation._decode_one(buf)
        self.bottom_image = ZcmCameraBaslerImagePresentation._decode_one(buf)
        self.sky_average_line = []
        for i0 in range(2):
            self.sky_average_line.append(ZcmCamWDSkylinePoint._decode_one(buf))
        self.point_count = struct.unpack(">i", buf.read(4))[0]
        self.sky_poly_line = []
        for i0 in range(self.point_count):
            self.sky_poly_line.append(ZcmCamWDSkylinePoint._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ZcmCamWDSkyline in parents: return 0
        newparents = parents + [ZcmCamWDSkyline]
        tmphash = (0xf0d1cb609daa9de8+ ZcmService._get_hash_recursive(newparents)+ ZcmCameraBaslerImagePresentation._get_hash_recursive(newparents)+ ZcmCameraBaslerImagePresentation._get_hash_recursive(newparents)+ ZcmCamWDSkylinePoint._get_hash_recursive(newparents)+ ZcmCamWDSkylinePoint._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ZcmCamWDSkyline._packed_fingerprint is None:
            ZcmCamWDSkyline._packed_fingerprint = struct.pack(">Q", ZcmCamWDSkyline._get_hash_recursive([]))
        return ZcmCamWDSkyline._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

