// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmLidarClusterBoundRect.h"

static int __ZcmLidarClusterBoundRect_hash_computed;
static uint64_t __ZcmLidarClusterBoundRect_hash;

uint64_t __ZcmLidarClusterBoundRect_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmLidarClusterBoundRect_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmLidarClusterBoundRect_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x59b052c9a88b3ddaLL
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmLidarClusterBoundRect_get_hash(void)
{
    if (!__ZcmLidarClusterBoundRect_hash_computed) {
        __ZcmLidarClusterBoundRect_hash = (int64_t)__ZcmLidarClusterBoundRect_hash_recursive(NULL);
        __ZcmLidarClusterBoundRect_hash_computed = 1;
    }

    return __ZcmLidarClusterBoundRect_hash;
}

int __ZcmLidarClusterBoundRect_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmLidarClusterBoundRect* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].top_left_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].top_left_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].top_right_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].top_right_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].bottom_left_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].bottom_left_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].bottom_right_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].bottom_right_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].center_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].center_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].angle), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmLidarClusterBoundRect_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmLidarClusterBoundRect* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmLidarClusterBoundRect_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmLidarClusterBoundRect_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmLidarClusterBoundRect_encoded_array_size(const ZcmLidarClusterBoundRect* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __float_encoded_array_size(&(p[element].top_left_x), 1);

        size += __float_encoded_array_size(&(p[element].top_left_y), 1);

        size += __float_encoded_array_size(&(p[element].top_right_x), 1);

        size += __float_encoded_array_size(&(p[element].top_right_y), 1);

        size += __float_encoded_array_size(&(p[element].bottom_left_x), 1);

        size += __float_encoded_array_size(&(p[element].bottom_left_y), 1);

        size += __float_encoded_array_size(&(p[element].bottom_right_x), 1);

        size += __float_encoded_array_size(&(p[element].bottom_right_y), 1);

        size += __float_encoded_array_size(&(p[element].center_x), 1);

        size += __float_encoded_array_size(&(p[element].center_y), 1);

        size += __float_encoded_array_size(&(p[element].width), 1);

        size += __float_encoded_array_size(&(p[element].height), 1);

        size += __float_encoded_array_size(&(p[element].angle), 1);

    }
    return size;
}

uint32_t ZcmLidarClusterBoundRect_encoded_size(const ZcmLidarClusterBoundRect* p)
{
    return 8 + __ZcmLidarClusterBoundRect_encoded_array_size(p, 1);
}

uint32_t ZcmLidarClusterBoundRect_struct_size(void)
{
    return sizeof(ZcmLidarClusterBoundRect);
}

uint32_t ZcmLidarClusterBoundRect_num_fields(void)
{
    return 13;
}

int ZcmLidarClusterBoundRect_get_field(const ZcmLidarClusterBoundRect* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmLidarClusterBoundRect_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "top_left_x";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->top_left_x;
            return 0;
        }
        
        case 1: {
            f->name = "top_left_y";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->top_left_y;
            return 0;
        }
        
        case 2: {
            f->name = "top_right_x";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->top_right_x;
            return 0;
        }
        
        case 3: {
            f->name = "top_right_y";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->top_right_y;
            return 0;
        }
        
        case 4: {
            f->name = "bottom_left_x";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->bottom_left_x;
            return 0;
        }
        
        case 5: {
            f->name = "bottom_left_y";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->bottom_left_y;
            return 0;
        }
        
        case 6: {
            f->name = "bottom_right_x";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->bottom_right_x;
            return 0;
        }
        
        case 7: {
            f->name = "bottom_right_y";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->bottom_right_y;
            return 0;
        }
        
        case 8: {
            f->name = "center_x";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->center_x;
            return 0;
        }
        
        case 9: {
            f->name = "center_y";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->center_y;
            return 0;
        }
        
        case 10: {
            f->name = "width";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->width;
            return 0;
        }
        
        case 11: {
            f->name = "height";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->height;
            return 0;
        }
        
        case 12: {
            f->name = "angle";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->angle;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmLidarClusterBoundRect_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmLidarClusterBoundRect_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmLidarClusterBoundRect_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmLidarClusterBoundRect_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmLidarClusterBoundRect_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmLidarClusterBoundRect_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmLidarClusterBoundRect_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmLidarClusterBoundRect_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmLidarClusterBoundRect_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmLidarClusterBoundRect_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmLidarClusterBoundRect* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].top_left_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].top_left_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].top_right_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].top_right_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].bottom_left_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].bottom_left_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].bottom_right_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].bottom_right_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].center_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].center_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].angle), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmLidarClusterBoundRect_decode_array_cleanup(ZcmLidarClusterBoundRect* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __float_decode_array_cleanup(&(p[element].top_left_x), 1);

        __float_decode_array_cleanup(&(p[element].top_left_y), 1);

        __float_decode_array_cleanup(&(p[element].top_right_x), 1);

        __float_decode_array_cleanup(&(p[element].top_right_y), 1);

        __float_decode_array_cleanup(&(p[element].bottom_left_x), 1);

        __float_decode_array_cleanup(&(p[element].bottom_left_y), 1);

        __float_decode_array_cleanup(&(p[element].bottom_right_x), 1);

        __float_decode_array_cleanup(&(p[element].bottom_right_y), 1);

        __float_decode_array_cleanup(&(p[element].center_x), 1);

        __float_decode_array_cleanup(&(p[element].center_y), 1);

        __float_decode_array_cleanup(&(p[element].width), 1);

        __float_decode_array_cleanup(&(p[element].height), 1);

        __float_decode_array_cleanup(&(p[element].angle), 1);

    }
    return 0;
}

int ZcmLidarClusterBoundRect_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmLidarClusterBoundRect* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmLidarClusterBoundRect_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmLidarClusterBoundRect_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmLidarClusterBoundRect_decode_cleanup(ZcmLidarClusterBoundRect* p)
{
    return __ZcmLidarClusterBoundRect_decode_array_cleanup(p, 1);
}

uint32_t __ZcmLidarClusterBoundRect_clone_array(const ZcmLidarClusterBoundRect* p, ZcmLidarClusterBoundRect* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __float_clone_array(&(p[element].top_left_x), &(q[element].top_left_x), 1);

        n += __float_clone_array(&(p[element].top_left_y), &(q[element].top_left_y), 1);

        n += __float_clone_array(&(p[element].top_right_x), &(q[element].top_right_x), 1);

        n += __float_clone_array(&(p[element].top_right_y), &(q[element].top_right_y), 1);

        n += __float_clone_array(&(p[element].bottom_left_x), &(q[element].bottom_left_x), 1);

        n += __float_clone_array(&(p[element].bottom_left_y), &(q[element].bottom_left_y), 1);

        n += __float_clone_array(&(p[element].bottom_right_x), &(q[element].bottom_right_x), 1);

        n += __float_clone_array(&(p[element].bottom_right_y), &(q[element].bottom_right_y), 1);

        n += __float_clone_array(&(p[element].center_x), &(q[element].center_x), 1);

        n += __float_clone_array(&(p[element].center_y), &(q[element].center_y), 1);

        n += __float_clone_array(&(p[element].width), &(q[element].width), 1);

        n += __float_clone_array(&(p[element].height), &(q[element].height), 1);

        n += __float_clone_array(&(p[element].angle), &(q[element].angle), 1);

    }
    return n;
}

ZcmLidarClusterBoundRect* ZcmLidarClusterBoundRect_copy(const ZcmLidarClusterBoundRect* p)
{
    ZcmLidarClusterBoundRect* q = (ZcmLidarClusterBoundRect*) malloc(sizeof(ZcmLidarClusterBoundRect));
    __ZcmLidarClusterBoundRect_clone_array(p, q, 1);
    return q;
}

void ZcmLidarClusterBoundRect_destroy(ZcmLidarClusterBoundRect* p)
{
    __ZcmLidarClusterBoundRect_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmLidarClusterBoundRect_publish(zcm_t* zcm, const char* channel, const ZcmLidarClusterBoundRect* p)
{
      uint32_t max_data_size = ZcmLidarClusterBoundRect_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmLidarClusterBoundRect_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmLidarClusterBoundRect_subscription_t {
    ZcmLidarClusterBoundRect_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmLidarClusterBoundRect_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmLidarClusterBoundRect p;
    memset(&p, 0, sizeof(ZcmLidarClusterBoundRect));
    status = ZcmLidarClusterBoundRect_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmLidarClusterBoundRect!!!\n", status);
        return;
    }

    ZcmLidarClusterBoundRect_subscription_t* h = (ZcmLidarClusterBoundRect_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmLidarClusterBoundRect_decode_cleanup (&p);
}

ZcmLidarClusterBoundRect_subscription_t* ZcmLidarClusterBoundRect_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmLidarClusterBoundRect_handler_t f, void* userdata)
{
    ZcmLidarClusterBoundRect_subscription_t* n = (ZcmLidarClusterBoundRect_subscription_t*)
                       malloc(sizeof(ZcmLidarClusterBoundRect_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmLidarClusterBoundRect_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmLidarClusterBoundRect ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmLidarClusterBoundRect_unsubscribe(zcm_t* zcm, ZcmLidarClusterBoundRect_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmLidarClusterBoundRect_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

