"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from ZcmLidarLuxPoint import ZcmLidarLuxPoint

from ZcmService import ZcmService

class ZcmLidarLuxDataScan(object):
    __slots__ = ["service", "scanNumber", "scannerStatus", "scannerHeight", "nbOfPoints", "scanPoints"]

    anglePerTick = 0.03125
    anglePerLayer = 0.8

    def __init__(self):
        self.service = ZcmService()
        self.scanNumber = 0
        self.scannerStatus = 0
        self.scannerHeight = 0.0
        self.nbOfPoints = 0
        self.scanPoints = []

    def encode(self):
        buf = BytesIO()
        buf.write(ZcmLidarLuxDataScan._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.service._get_packed_fingerprint() == ZcmService._get_packed_fingerprint()
        self.service._encode_one(buf)
        buf.write(struct.pack(">iifi", self.scanNumber, self.scannerStatus, self.scannerHeight, self.nbOfPoints))
        for i0 in range(self.nbOfPoints):
            assert self.scanPoints[i0]._get_packed_fingerprint() == ZcmLidarLuxPoint._get_packed_fingerprint()
            self.scanPoints[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ZcmLidarLuxDataScan._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ZcmLidarLuxDataScan._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ZcmLidarLuxDataScan()
        self.service = ZcmService._decode_one(buf)
        self.scanNumber, self.scannerStatus, self.scannerHeight, self.nbOfPoints = struct.unpack(">iifi", buf.read(16))
        self.scanPoints = []
        for i0 in range(self.nbOfPoints):
            self.scanPoints.append(ZcmLidarLuxPoint._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ZcmLidarLuxDataScan in parents: return 0
        newparents = parents + [ZcmLidarLuxDataScan]
        tmphash = (0x96592ea9f5135e04+ ZcmService._get_hash_recursive(newparents)+ ZcmLidarLuxPoint._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ZcmLidarLuxDataScan._packed_fingerprint is None:
            ZcmLidarLuxDataScan._packed_fingerprint = struct.pack(">Q", ZcmLidarLuxDataScan._get_hash_recursive([]))
        return ZcmLidarLuxDataScan._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

