"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ZcmUtmCoord(object):
    __slots__ = ["easting", "northing", "zone", "zone_letter"]

    def __init__(self):
        self.easting = 0.0
        self.northing = 0.0
        self.zone = 0
        self.zone_letter = ""

    def encode(self):
        buf = BytesIO()
        buf.write(ZcmUtmCoord._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddi", self.easting, self.northing, self.zone))
        __zone_letter_encoded = self.zone_letter.encode('utf-8')
        buf.write(struct.pack('>I', len(__zone_letter_encoded)+1))
        buf.write(__zone_letter_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ZcmUtmCoord._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ZcmUtmCoord._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ZcmUtmCoord()
        self.easting, self.northing, self.zone = struct.unpack(">ddi", buf.read(20))
        __zone_letter_len = struct.unpack('>I', buf.read(4))[0]
        self.zone_letter = buf.read(__zone_letter_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ZcmUtmCoord in parents: return 0
        tmphash = (0x594d1a18c3249460) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ZcmUtmCoord._packed_fingerprint is None:
            ZcmUtmCoord._packed_fingerprint = struct.pack(">Q", ZcmUtmCoord._get_hash_recursive([]))
        return ZcmUtmCoord._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

