// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm/zcm_coretypes.h>
#include <zcm/zcm.h>

#ifndef _ZcmRadarContiObjectGeneralInfo_h
#define _ZcmRadarContiObjectGeneralInfo_h

#ifdef __cplusplus
extern "C" {
#endif

#include "ZcmService.h"
/**
 * @struct ZcmRadarContiObjectGeneralInfo
 * @brief Информация о расположении и скорости объектов.
 * Сообщение приходит для каждого обнаруженного объекта \n
 * ID: 0x60B
 * @var ZcmRadarContiObjectGeneralInfo::id
 * @brief - ID объекта (от 0 до 255)
 * @var ZcmRadarContiObjectGeneralInfo::dist_long
 * @brief - координата по оси X (м) (от -500 до 1138.2)
 * @var ZcmRadarContiObjectGeneralInfo::dist_lat
 * @brief - координата по оси Y (м) (от -102.3 до 102.3)
 * @var ZcmRadarContiObjectGeneralInfo::vrel_long
 * @brief - относительная скорость по оси X (м/с) (от -128 до 127.75)
 * @var ZcmRadarContiObjectGeneralInfo::dyn_prop
 * @brief - Динамическая характеристика объекта: \n
 *                  0 - moving \n
 *                  1 - stationary \n
 *                  2 - oncoming \n
 *                  3 - stationary candidate \n
 *                  4 - unknown \n
 *                  5 - crossing stationary \n
 *                  6 - crossing moving \n
 *                  7 - stopped \n
 *                  
 * @var ZcmRadarContiObjectGeneralInfo::vrel_lat
 * @brief - относительная скорость по оси Y (м/с) (от -64 до 63.75)
 * @var ZcmRadarContiObjectGeneralInfo::rcs
 * @brief - эффективная площадь отражения (dBm2)  (от -64 до 63.5) 
 *
 */
typedef struct _ZcmRadarContiObjectGeneralInfo ZcmRadarContiObjectGeneralInfo;
struct _ZcmRadarContiObjectGeneralInfo
{
    ZcmService service;
    int16_t    id;
    float      dist_long;
    float      dist_lat;
    float      vrel_long;
    int8_t     dyn_prop;
    float      vrel_lat;
    float      rcs;
};

/**
 * Create a deep copy of a ZcmRadarContiObjectGeneralInfo.
 * When no longer needed, destroy it with ZcmRadarContiObjectGeneralInfo_destroy()
 */
ZcmRadarContiObjectGeneralInfo* ZcmRadarContiObjectGeneralInfo_copy(const ZcmRadarContiObjectGeneralInfo* to_copy);

/**
 * Destroy an instance of ZcmRadarContiObjectGeneralInfo created by ZcmRadarContiObjectGeneralInfo_copy()
 */
void ZcmRadarContiObjectGeneralInfo_destroy(ZcmRadarContiObjectGeneralInfo* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _ZcmRadarContiObjectGeneralInfo_subscription_t ZcmRadarContiObjectGeneralInfo_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * ZcmRadarContiObjectGeneralInfo is received.
 */
typedef void(*ZcmRadarContiObjectGeneralInfo_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const ZcmRadarContiObjectGeneralInfo* msg, void* userdata);

/**
 * Publish a message of type ZcmRadarContiObjectGeneralInfo using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int ZcmRadarContiObjectGeneralInfo_publish(zcm_t* zcm, const char* channel, const ZcmRadarContiObjectGeneralInfo* msg);

/**
 * Subscribe to messages of type ZcmRadarContiObjectGeneralInfo using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to ZcmRadarContiObjectGeneralInfo_unsubscribe.
 */
ZcmRadarContiObjectGeneralInfo_subscription_t* ZcmRadarContiObjectGeneralInfo_subscribe(zcm_t* zcm, const char* channel, ZcmRadarContiObjectGeneralInfo_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by ZcmRadarContiObjectGeneralInfo_subscribe()
 */
int ZcmRadarContiObjectGeneralInfo_unsubscribe(zcm_t* zcm, ZcmRadarContiObjectGeneralInfo_subscription_t* hid);
/**
 * Encode a message of type ZcmRadarContiObjectGeneralInfo into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to ZcmRadarContiObjectGeneralInfo_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int ZcmRadarContiObjectGeneralInfo_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmRadarContiObjectGeneralInfo* p);

/**
 * Decode a message of type ZcmRadarContiObjectGeneralInfo from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with ZcmRadarContiObjectGeneralInfo_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int ZcmRadarContiObjectGeneralInfo_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmRadarContiObjectGeneralInfo* msg);

/**
 * Release resources allocated by ZcmRadarContiObjectGeneralInfo_decode()
 * @return 0
 */
int ZcmRadarContiObjectGeneralInfo_decode_cleanup(ZcmRadarContiObjectGeneralInfo* p);

/**
 * Check how many bytes are required to encode a message of type ZcmRadarContiObjectGeneralInfo
 */
uint32_t ZcmRadarContiObjectGeneralInfo_encoded_size(const ZcmRadarContiObjectGeneralInfo* p);
uint32_t ZcmRadarContiObjectGeneralInfo_struct_size(void);
uint32_t ZcmRadarContiObjectGeneralInfo_num_fields(void);
int      ZcmRadarContiObjectGeneralInfo_get_field(const ZcmRadarContiObjectGeneralInfo* p, uint32_t i, zcm_field_t* f);
const zcm_type_info_t* ZcmRadarContiObjectGeneralInfo_get_type_info(void);

// ZCM support functions. Users should not call these
int64_t  __ZcmRadarContiObjectGeneralInfo_get_hash(void);
uint64_t __ZcmRadarContiObjectGeneralInfo_hash_recursive(const __zcm_hash_ptr* p);
int      __ZcmRadarContiObjectGeneralInfo_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmRadarContiObjectGeneralInfo* p, uint32_t elements);
int      __ZcmRadarContiObjectGeneralInfo_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmRadarContiObjectGeneralInfo* p, uint32_t elements);
int      __ZcmRadarContiObjectGeneralInfo_decode_array_cleanup(ZcmRadarContiObjectGeneralInfo* p, uint32_t elements);
uint32_t __ZcmRadarContiObjectGeneralInfo_encoded_array_size(const ZcmRadarContiObjectGeneralInfo* p, uint32_t elements);
uint32_t __ZcmRadarContiObjectGeneralInfo_clone_array(const ZcmRadarContiObjectGeneralInfo* p, ZcmRadarContiObjectGeneralInfo* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
