// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmRadarContiObject.h"

static int __ZcmRadarContiObject_hash_computed;
static uint64_t __ZcmRadarContiObject_hash;

uint64_t __ZcmRadarContiObject_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmRadarContiObject_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmRadarContiObject_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xfab290666d206f02LL
         + __int16_t_hash_recursive(&cp)
         + __ZcmRadarContiObjectGeneralInfo_hash_recursive(&cp)
         + __ZcmRadarContiObjectQualityInfo_hash_recursive(&cp)
         + __ZcmRadarContiObjectExtendedInfo_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmRadarContiObject_get_hash(void)
{
    if (!__ZcmRadarContiObject_hash_computed) {
        __ZcmRadarContiObject_hash = (int64_t)__ZcmRadarContiObject_hash_recursive(NULL);
        __ZcmRadarContiObject_hash_computed = 1;
    }

    return __ZcmRadarContiObject_hash;
}

int __ZcmRadarContiObject_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmRadarContiObject* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmRadarContiObjectGeneralInfo_encode_array(buf, offset + pos, maxlen - pos, &(p[element].general), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmRadarContiObjectQualityInfo_encode_array(buf, offset + pos, maxlen - pos, &(p[element].quality), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmRadarContiObjectExtendedInfo_encode_array(buf, offset + pos, maxlen - pos, &(p[element].extended), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmRadarContiObject_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmRadarContiObject* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmRadarContiObject_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmRadarContiObject_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmRadarContiObject_encoded_array_size(const ZcmRadarContiObject* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __int16_t_encoded_array_size(&(p[element].id), 1);

        size += __ZcmRadarContiObjectGeneralInfo_encoded_array_size(&(p[element].general), 1);

        size += __ZcmRadarContiObjectQualityInfo_encoded_array_size(&(p[element].quality), 1);

        size += __ZcmRadarContiObjectExtendedInfo_encoded_array_size(&(p[element].extended), 1);

    }
    return size;
}

uint32_t ZcmRadarContiObject_encoded_size(const ZcmRadarContiObject* p)
{
    return 8 + __ZcmRadarContiObject_encoded_array_size(p, 1);
}

uint32_t ZcmRadarContiObject_struct_size(void)
{
    return sizeof(ZcmRadarContiObject);
}

uint32_t ZcmRadarContiObject_num_fields(void)
{
    return 4;
}

int ZcmRadarContiObject_get_field(const ZcmRadarContiObject* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmRadarContiObject_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "id";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->id;
            return 0;
        }
        
        case 1: {
            /* ZcmRadarContiObjectGeneralInfo */
            f->name = "general";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmRadarContiObjectGeneralInfo";
            f->num_dim = 0;
            f->data = (void*) &p->general;
            return 0;
        }
        
        case 2: {
            /* ZcmRadarContiObjectQualityInfo */
            f->name = "quality";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmRadarContiObjectQualityInfo";
            f->num_dim = 0;
            f->data = (void*) &p->quality;
            return 0;
        }
        
        case 3: {
            /* ZcmRadarContiObjectExtendedInfo */
            f->name = "extended";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmRadarContiObjectExtendedInfo";
            f->num_dim = 0;
            f->data = (void*) &p->extended;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmRadarContiObject_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmRadarContiObject_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmRadarContiObject_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmRadarContiObject_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmRadarContiObject_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmRadarContiObject_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmRadarContiObject_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmRadarContiObject_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmRadarContiObject_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmRadarContiObject_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmRadarContiObject* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmRadarContiObjectGeneralInfo_decode_array(buf, offset + pos, maxlen - pos, &(p[element].general), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmRadarContiObjectQualityInfo_decode_array(buf, offset + pos, maxlen - pos, &(p[element].quality), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmRadarContiObjectExtendedInfo_decode_array(buf, offset + pos, maxlen - pos, &(p[element].extended), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmRadarContiObject_decode_array_cleanup(ZcmRadarContiObject* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __int16_t_decode_array_cleanup(&(p[element].id), 1);

        __ZcmRadarContiObjectGeneralInfo_decode_array_cleanup(&(p[element].general), 1);

        __ZcmRadarContiObjectQualityInfo_decode_array_cleanup(&(p[element].quality), 1);

        __ZcmRadarContiObjectExtendedInfo_decode_array_cleanup(&(p[element].extended), 1);

    }
    return 0;
}

int ZcmRadarContiObject_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmRadarContiObject* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmRadarContiObject_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmRadarContiObject_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmRadarContiObject_decode_cleanup(ZcmRadarContiObject* p)
{
    return __ZcmRadarContiObject_decode_array_cleanup(p, 1);
}

uint32_t __ZcmRadarContiObject_clone_array(const ZcmRadarContiObject* p, ZcmRadarContiObject* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __int16_t_clone_array(&(p[element].id), &(q[element].id), 1);

        n += __ZcmRadarContiObjectGeneralInfo_clone_array(&(p[element].general), &(q[element].general), 1);

        n += __ZcmRadarContiObjectQualityInfo_clone_array(&(p[element].quality), &(q[element].quality), 1);

        n += __ZcmRadarContiObjectExtendedInfo_clone_array(&(p[element].extended), &(q[element].extended), 1);

    }
    return n;
}

ZcmRadarContiObject* ZcmRadarContiObject_copy(const ZcmRadarContiObject* p)
{
    ZcmRadarContiObject* q = (ZcmRadarContiObject*) malloc(sizeof(ZcmRadarContiObject));
    __ZcmRadarContiObject_clone_array(p, q, 1);
    return q;
}

void ZcmRadarContiObject_destroy(ZcmRadarContiObject* p)
{
    __ZcmRadarContiObject_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmRadarContiObject_publish(zcm_t* zcm, const char* channel, const ZcmRadarContiObject* p)
{
      uint32_t max_data_size = ZcmRadarContiObject_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmRadarContiObject_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmRadarContiObject_subscription_t {
    ZcmRadarContiObject_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmRadarContiObject_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmRadarContiObject p;
    memset(&p, 0, sizeof(ZcmRadarContiObject));
    status = ZcmRadarContiObject_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmRadarContiObject!!!\n", status);
        return;
    }

    ZcmRadarContiObject_subscription_t* h = (ZcmRadarContiObject_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmRadarContiObject_decode_cleanup (&p);
}

ZcmRadarContiObject_subscription_t* ZcmRadarContiObject_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmRadarContiObject_handler_t f, void* userdata)
{
    ZcmRadarContiObject_subscription_t* n = (ZcmRadarContiObject_subscription_t*)
                       malloc(sizeof(ZcmRadarContiObject_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmRadarContiObject_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmRadarContiObject ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmRadarContiObject_unsubscribe(zcm_t* zcm, ZcmRadarContiObject_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmRadarContiObject_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

