// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmRadarContiObjectsScan.h"

static int __ZcmRadarContiObjectsScan_hash_computed;
static uint64_t __ZcmRadarContiObjectsScan_hash;

uint64_t __ZcmRadarContiObjectsScan_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmRadarContiObjectsScan_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmRadarContiObjectsScan_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x1e5c1c41dd02102cLL
         + __ZcmService_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __ZcmRadarContiObject_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmRadarContiObjectsScan_get_hash(void)
{
    if (!__ZcmRadarContiObjectsScan_hash_computed) {
        __ZcmRadarContiObjectsScan_hash = (int64_t)__ZcmRadarContiObjectsScan_hash_recursive(NULL);
        __ZcmRadarContiObjectsScan_hash_computed = 1;
    }

    return __ZcmRadarContiObjectsScan_hash;
}

int __ZcmRadarContiObjectsScan_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmRadarContiObjectsScan* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __ZcmService_encode_array(buf, offset + pos, maxlen - pos, &(p[element].service), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].scan_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmRadarContiObject_encode_array(buf, offset + pos, maxlen - pos, p[element].objects, p[element].scan_size);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmRadarContiObjectsScan_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmRadarContiObjectsScan* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmRadarContiObjectsScan_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmRadarContiObjectsScan_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmRadarContiObjectsScan_encoded_array_size(const ZcmRadarContiObjectsScan* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __ZcmService_encoded_array_size(&(p[element].service), 1);

        size += __int16_t_encoded_array_size(&(p[element].scan_size), 1);

        size += __ZcmRadarContiObject_encoded_array_size(p[element].objects, p[element].scan_size);

    }
    return size;
}

uint32_t ZcmRadarContiObjectsScan_encoded_size(const ZcmRadarContiObjectsScan* p)
{
    return 8 + __ZcmRadarContiObjectsScan_encoded_array_size(p, 1);
}

uint32_t ZcmRadarContiObjectsScan_struct_size(void)
{
    return sizeof(ZcmRadarContiObjectsScan);
}

uint32_t ZcmRadarContiObjectsScan_num_fields(void)
{
    return 3;
}

int ZcmRadarContiObjectsScan_get_field(const ZcmRadarContiObjectsScan* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmRadarContiObjectsScan_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            /* ZcmService */
            f->name = "service";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmService";
            f->num_dim = 0;
            f->data = (void*) &p->service;
            return 0;
        }
        
        case 1: {
            f->name = "scan_size";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->scan_size;
            return 0;
        }
        
        case 2: {
            /* ZcmRadarContiObject */
            f->name = "objects";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmRadarContiObject";
            f->num_dim = 1;
            f->dim_size[0] = p->scan_size;
            f->dim_is_variable[0] = 1;
            f->data = (void*) &p->objects;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmRadarContiObjectsScan_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmRadarContiObjectsScan_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmRadarContiObjectsScan_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmRadarContiObjectsScan_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmRadarContiObjectsScan_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmRadarContiObjectsScan_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmRadarContiObjectsScan_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmRadarContiObjectsScan_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmRadarContiObjectsScan_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmRadarContiObjectsScan_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmRadarContiObjectsScan* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __ZcmService_decode_array(buf, offset + pos, maxlen - pos, &(p[element].service), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].scan_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].objects = (ZcmRadarContiObject*) zcm_malloc(sizeof(ZcmRadarContiObject) * p[element].scan_size);
        thislen = __ZcmRadarContiObject_decode_array(buf, offset + pos, maxlen - pos, p[element].objects, p[element].scan_size);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmRadarContiObjectsScan_decode_array_cleanup(ZcmRadarContiObjectsScan* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __ZcmService_decode_array_cleanup(&(p[element].service), 1);

        __int16_t_decode_array_cleanup(&(p[element].scan_size), 1);

        __ZcmRadarContiObject_decode_array_cleanup(p[element].objects, p[element].scan_size);
        if (p[element].objects) free(p[element].objects);

    }
    return 0;
}

int ZcmRadarContiObjectsScan_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmRadarContiObjectsScan* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmRadarContiObjectsScan_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmRadarContiObjectsScan_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmRadarContiObjectsScan_decode_cleanup(ZcmRadarContiObjectsScan* p)
{
    return __ZcmRadarContiObjectsScan_decode_array_cleanup(p, 1);
}

uint32_t __ZcmRadarContiObjectsScan_clone_array(const ZcmRadarContiObjectsScan* p, ZcmRadarContiObjectsScan* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __ZcmService_clone_array(&(p[element].service), &(q[element].service), 1);

        n += __int16_t_clone_array(&(p[element].scan_size), &(q[element].scan_size), 1);

        q[element].objects = (ZcmRadarContiObject*) zcm_malloc(sizeof(ZcmRadarContiObject) * q[element].scan_size);
        n += __ZcmRadarContiObject_clone_array(p[element].objects, q[element].objects, p[element].scan_size);

    }
    return n;
}

ZcmRadarContiObjectsScan* ZcmRadarContiObjectsScan_copy(const ZcmRadarContiObjectsScan* p)
{
    ZcmRadarContiObjectsScan* q = (ZcmRadarContiObjectsScan*) malloc(sizeof(ZcmRadarContiObjectsScan));
    __ZcmRadarContiObjectsScan_clone_array(p, q, 1);
    return q;
}

void ZcmRadarContiObjectsScan_destroy(ZcmRadarContiObjectsScan* p)
{
    __ZcmRadarContiObjectsScan_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmRadarContiObjectsScan_publish(zcm_t* zcm, const char* channel, const ZcmRadarContiObjectsScan* p)
{
      uint32_t max_data_size = ZcmRadarContiObjectsScan_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmRadarContiObjectsScan_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmRadarContiObjectsScan_subscription_t {
    ZcmRadarContiObjectsScan_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmRadarContiObjectsScan_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmRadarContiObjectsScan p;
    memset(&p, 0, sizeof(ZcmRadarContiObjectsScan));
    status = ZcmRadarContiObjectsScan_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmRadarContiObjectsScan!!!\n", status);
        return;
    }

    ZcmRadarContiObjectsScan_subscription_t* h = (ZcmRadarContiObjectsScan_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmRadarContiObjectsScan_decode_cleanup (&p);
}

ZcmRadarContiObjectsScan_subscription_t* ZcmRadarContiObjectsScan_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmRadarContiObjectsScan_handler_t f, void* userdata)
{
    ZcmRadarContiObjectsScan_subscription_t* n = (ZcmRadarContiObjectsScan_subscription_t*)
                       malloc(sizeof(ZcmRadarContiObjectsScan_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmRadarContiObjectsScan_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmRadarContiObjectsScan ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmRadarContiObjectsScan_unsubscribe(zcm_t* zcm, ZcmRadarContiObjectsScan_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmRadarContiObjectsScan_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

