// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm/zcm_coretypes.h>
#include <zcm/zcm.h>

#ifndef _ZcmSauglOduCommand_h
#define _ZcmSauglOduCommand_h

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @struct ZcmSauglOduCommand
 * @brief Информация блока обнаружения препятствий о командах управления
 * @var ZcmSauglOduCommand::is_signal
 * @brief - признак команды подачи сигнала
 * @var ZcmSauglOduCommand::is_brake
 * @brief - признак команды полного служебного торможения
 *
 */
typedef struct _ZcmSauglOduCommand ZcmSauglOduCommand;
struct _ZcmSauglOduCommand
{
    int8_t     is_signal;
    int8_t     is_brake;
};

/**
 * Create a deep copy of a ZcmSauglOduCommand.
 * When no longer needed, destroy it with ZcmSauglOduCommand_destroy()
 */
ZcmSauglOduCommand* ZcmSauglOduCommand_copy(const ZcmSauglOduCommand* to_copy);

/**
 * Destroy an instance of ZcmSauglOduCommand created by ZcmSauglOduCommand_copy()
 */
void ZcmSauglOduCommand_destroy(ZcmSauglOduCommand* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _ZcmSauglOduCommand_subscription_t ZcmSauglOduCommand_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * ZcmSauglOduCommand is received.
 */
typedef void(*ZcmSauglOduCommand_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const ZcmSauglOduCommand* msg, void* userdata);

/**
 * Publish a message of type ZcmSauglOduCommand using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int ZcmSauglOduCommand_publish(zcm_t* zcm, const char* channel, const ZcmSauglOduCommand* msg);

/**
 * Subscribe to messages of type ZcmSauglOduCommand using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to ZcmSauglOduCommand_unsubscribe.
 */
ZcmSauglOduCommand_subscription_t* ZcmSauglOduCommand_subscribe(zcm_t* zcm, const char* channel, ZcmSauglOduCommand_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by ZcmSauglOduCommand_subscribe()
 */
int ZcmSauglOduCommand_unsubscribe(zcm_t* zcm, ZcmSauglOduCommand_subscription_t* hid);
/**
 * Encode a message of type ZcmSauglOduCommand into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to ZcmSauglOduCommand_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int ZcmSauglOduCommand_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmSauglOduCommand* p);

/**
 * Decode a message of type ZcmSauglOduCommand from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with ZcmSauglOduCommand_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int ZcmSauglOduCommand_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmSauglOduCommand* msg);

/**
 * Release resources allocated by ZcmSauglOduCommand_decode()
 * @return 0
 */
int ZcmSauglOduCommand_decode_cleanup(ZcmSauglOduCommand* p);

/**
 * Check how many bytes are required to encode a message of type ZcmSauglOduCommand
 */
uint32_t ZcmSauglOduCommand_encoded_size(const ZcmSauglOduCommand* p);
uint32_t ZcmSauglOduCommand_struct_size(void);
uint32_t ZcmSauglOduCommand_num_fields(void);
int      ZcmSauglOduCommand_get_field(const ZcmSauglOduCommand* p, uint32_t i, zcm_field_t* f);
const zcm_type_info_t* ZcmSauglOduCommand_get_type_info(void);

// ZCM support functions. Users should not call these
int64_t  __ZcmSauglOduCommand_get_hash(void);
uint64_t __ZcmSauglOduCommand_hash_recursive(const __zcm_hash_ptr* p);
int      __ZcmSauglOduCommand_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmSauglOduCommand* p, uint32_t elements);
int      __ZcmSauglOduCommand_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmSauglOduCommand* p, uint32_t elements);
int      __ZcmSauglOduCommand_decode_array_cleanup(ZcmSauglOduCommand* p, uint32_t elements);
uint32_t __ZcmSauglOduCommand_encoded_array_size(const ZcmSauglOduCommand* p, uint32_t elements);
uint32_t __ZcmSauglOduCommand_clone_array(const ZcmSauglOduCommand* p, ZcmSauglOduCommand* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
