// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmSauglState.h"

static int __ZcmSauglState_hash_computed;
static uint64_t __ZcmSauglState_hash;

uint64_t __ZcmSauglState_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmSauglState_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmSauglState_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x1cb213138e185178LL
         + __ZcmService_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmSauglState_get_hash(void)
{
    if (!__ZcmSauglState_hash_computed) {
        __ZcmSauglState_hash = (int64_t)__ZcmSauglState_hash_recursive(NULL);
        __ZcmSauglState_hash_computed = 1;
    }

    return __ZcmSauglState_hash;
}

int __ZcmSauglState_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmSauglState* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __ZcmService_encode_array(buf, offset + pos, maxlen - pos, &(p[element].service), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].power), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].brake), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].reversor), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].mode), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].mals_operation), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].pressure), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].hold_speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmSauglState_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmSauglState* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmSauglState_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmSauglState_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmSauglState_encoded_array_size(const ZcmSauglState* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __ZcmService_encoded_array_size(&(p[element].service), 1);

        size += __int8_t_encoded_array_size(&(p[element].power), 1);

        size += __int16_t_encoded_array_size(&(p[element].brake), 1);

        size += __int8_t_encoded_array_size(&(p[element].reversor), 1);

        size += __int8_t_encoded_array_size(&(p[element].mode), 1);

        size += __int8_t_encoded_array_size(&(p[element].mals_operation), 1);

        size += __int16_t_encoded_array_size(&(p[element].pressure), 1);

        size += __int16_t_encoded_array_size(&(p[element].speed), 1);

        size += __int16_t_encoded_array_size(&(p[element].hold_speed), 1);

    }
    return size;
}

uint32_t ZcmSauglState_encoded_size(const ZcmSauglState* p)
{
    return 8 + __ZcmSauglState_encoded_array_size(p, 1);
}

uint32_t ZcmSauglState_struct_size(void)
{
    return sizeof(ZcmSauglState);
}

uint32_t ZcmSauglState_num_fields(void)
{
    return 9;
}

int ZcmSauglState_get_field(const ZcmSauglState* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmSauglState_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            /* ZcmService */
            f->name = "service";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmService";
            f->num_dim = 0;
            f->data = (void*) &p->service;
            return 0;
        }
        
        case 1: {
            f->name = "power";
            f->type = ZCM_FIELD_INT8_T;
            f->typestr = "int8_t";
            f->num_dim = 0;
            f->data = (void*) &p->power;
            return 0;
        }
        
        case 2: {
            f->name = "brake";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->brake;
            return 0;
        }
        
        case 3: {
            f->name = "reversor";
            f->type = ZCM_FIELD_INT8_T;
            f->typestr = "int8_t";
            f->num_dim = 0;
            f->data = (void*) &p->reversor;
            return 0;
        }
        
        case 4: {
            f->name = "mode";
            f->type = ZCM_FIELD_INT8_T;
            f->typestr = "int8_t";
            f->num_dim = 0;
            f->data = (void*) &p->mode;
            return 0;
        }
        
        case 5: {
            f->name = "mals_operation";
            f->type = ZCM_FIELD_INT8_T;
            f->typestr = "int8_t";
            f->num_dim = 0;
            f->data = (void*) &p->mals_operation;
            return 0;
        }
        
        case 6: {
            f->name = "pressure";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->pressure;
            return 0;
        }
        
        case 7: {
            f->name = "speed";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->speed;
            return 0;
        }
        
        case 8: {
            f->name = "hold_speed";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->hold_speed;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmSauglState_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmSauglState_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmSauglState_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmSauglState_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmSauglState_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmSauglState_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmSauglState_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmSauglState_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmSauglState_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmSauglState_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmSauglState* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __ZcmService_decode_array(buf, offset + pos, maxlen - pos, &(p[element].service), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].power), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].brake), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].reversor), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].mode), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].mals_operation), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].pressure), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].hold_speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmSauglState_decode_array_cleanup(ZcmSauglState* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __ZcmService_decode_array_cleanup(&(p[element].service), 1);

        __int8_t_decode_array_cleanup(&(p[element].power), 1);

        __int16_t_decode_array_cleanup(&(p[element].brake), 1);

        __int8_t_decode_array_cleanup(&(p[element].reversor), 1);

        __int8_t_decode_array_cleanup(&(p[element].mode), 1);

        __int8_t_decode_array_cleanup(&(p[element].mals_operation), 1);

        __int16_t_decode_array_cleanup(&(p[element].pressure), 1);

        __int16_t_decode_array_cleanup(&(p[element].speed), 1);

        __int16_t_decode_array_cleanup(&(p[element].hold_speed), 1);

    }
    return 0;
}

int ZcmSauglState_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmSauglState* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmSauglState_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmSauglState_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmSauglState_decode_cleanup(ZcmSauglState* p)
{
    return __ZcmSauglState_decode_array_cleanup(p, 1);
}

uint32_t __ZcmSauglState_clone_array(const ZcmSauglState* p, ZcmSauglState* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __ZcmService_clone_array(&(p[element].service), &(q[element].service), 1);

        n += __int8_t_clone_array(&(p[element].power), &(q[element].power), 1);

        n += __int16_t_clone_array(&(p[element].brake), &(q[element].brake), 1);

        n += __int8_t_clone_array(&(p[element].reversor), &(q[element].reversor), 1);

        n += __int8_t_clone_array(&(p[element].mode), &(q[element].mode), 1);

        n += __int8_t_clone_array(&(p[element].mals_operation), &(q[element].mals_operation), 1);

        n += __int16_t_clone_array(&(p[element].pressure), &(q[element].pressure), 1);

        n += __int16_t_clone_array(&(p[element].speed), &(q[element].speed), 1);

        n += __int16_t_clone_array(&(p[element].hold_speed), &(q[element].hold_speed), 1);

    }
    return n;
}

ZcmSauglState* ZcmSauglState_copy(const ZcmSauglState* p)
{
    ZcmSauglState* q = (ZcmSauglState*) malloc(sizeof(ZcmSauglState));
    __ZcmSauglState_clone_array(p, q, 1);
    return q;
}

void ZcmSauglState_destroy(ZcmSauglState* p)
{
    __ZcmSauglState_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmSauglState_publish(zcm_t* zcm, const char* channel, const ZcmSauglState* p)
{
      uint32_t max_data_size = ZcmSauglState_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmSauglState_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmSauglState_subscription_t {
    ZcmSauglState_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmSauglState_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmSauglState p;
    memset(&p, 0, sizeof(ZcmSauglState));
    status = ZcmSauglState_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmSauglState!!!\n", status);
        return;
    }

    ZcmSauglState_subscription_t* h = (ZcmSauglState_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmSauglState_decode_cleanup (&p);
}

ZcmSauglState_subscription_t* ZcmSauglState_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmSauglState_handler_t f, void* userdata)
{
    ZcmSauglState_subscription_t* n = (ZcmSauglState_subscription_t*)
                       malloc(sizeof(ZcmSauglState_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmSauglState_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmSauglState ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmSauglState_unsubscribe(zcm_t* zcm, ZcmSauglState_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmSauglState_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

