// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm/zcm_coretypes.h>
#include <zcm/zcm.h>

#ifndef _ZcmStereoPairPoint2D_h
#define _ZcmStereoPairPoint2D_h

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @mainpage Результат поиска препятствий от стереопары 
 * @struct ZcmStereoPairPoint2D
 * @brief Сообщение содержит координаты точки относительно общей системы координат
 * @var ZcmStereoPairPoint2D::x
 * @brief - смещение точки по оси x
 * @var ZcmStereoPairPoint2D::y
 * @brief - смещение точки по оси y
 *
 */
typedef struct _ZcmStereoPairPoint2D ZcmStereoPairPoint2D;
struct _ZcmStereoPairPoint2D
{
    double     x;
    double     y;
};

/**
 * Create a deep copy of a ZcmStereoPairPoint2D.
 * When no longer needed, destroy it with ZcmStereoPairPoint2D_destroy()
 */
ZcmStereoPairPoint2D* ZcmStereoPairPoint2D_copy(const ZcmStereoPairPoint2D* to_copy);

/**
 * Destroy an instance of ZcmStereoPairPoint2D created by ZcmStereoPairPoint2D_copy()
 */
void ZcmStereoPairPoint2D_destroy(ZcmStereoPairPoint2D* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _ZcmStereoPairPoint2D_subscription_t ZcmStereoPairPoint2D_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * ZcmStereoPairPoint2D is received.
 */
typedef void(*ZcmStereoPairPoint2D_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const ZcmStereoPairPoint2D* msg, void* userdata);

/**
 * Publish a message of type ZcmStereoPairPoint2D using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int ZcmStereoPairPoint2D_publish(zcm_t* zcm, const char* channel, const ZcmStereoPairPoint2D* msg);

/**
 * Subscribe to messages of type ZcmStereoPairPoint2D using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to ZcmStereoPairPoint2D_unsubscribe.
 */
ZcmStereoPairPoint2D_subscription_t* ZcmStereoPairPoint2D_subscribe(zcm_t* zcm, const char* channel, ZcmStereoPairPoint2D_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by ZcmStereoPairPoint2D_subscribe()
 */
int ZcmStereoPairPoint2D_unsubscribe(zcm_t* zcm, ZcmStereoPairPoint2D_subscription_t* hid);
/**
 * Encode a message of type ZcmStereoPairPoint2D into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to ZcmStereoPairPoint2D_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int ZcmStereoPairPoint2D_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmStereoPairPoint2D* p);

/**
 * Decode a message of type ZcmStereoPairPoint2D from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with ZcmStereoPairPoint2D_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int ZcmStereoPairPoint2D_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmStereoPairPoint2D* msg);

/**
 * Release resources allocated by ZcmStereoPairPoint2D_decode()
 * @return 0
 */
int ZcmStereoPairPoint2D_decode_cleanup(ZcmStereoPairPoint2D* p);

/**
 * Check how many bytes are required to encode a message of type ZcmStereoPairPoint2D
 */
uint32_t ZcmStereoPairPoint2D_encoded_size(const ZcmStereoPairPoint2D* p);
uint32_t ZcmStereoPairPoint2D_struct_size(void);
uint32_t ZcmStereoPairPoint2D_num_fields(void);
int      ZcmStereoPairPoint2D_get_field(const ZcmStereoPairPoint2D* p, uint32_t i, zcm_field_t* f);
const zcm_type_info_t* ZcmStereoPairPoint2D_get_type_info(void);

// ZCM support functions. Users should not call these
int64_t  __ZcmStereoPairPoint2D_get_hash(void);
uint64_t __ZcmStereoPairPoint2D_hash_recursive(const __zcm_hash_ptr* p);
int      __ZcmStereoPairPoint2D_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmStereoPairPoint2D* p, uint32_t elements);
int      __ZcmStereoPairPoint2D_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmStereoPairPoint2D* p, uint32_t elements);
int      __ZcmStereoPairPoint2D_decode_array_cleanup(ZcmStereoPairPoint2D* p, uint32_t elements);
uint32_t __ZcmStereoPairPoint2D_encoded_array_size(const ZcmStereoPairPoint2D* p, uint32_t elements);
uint32_t __ZcmStereoPairPoint2D_clone_array(const ZcmStereoPairPoint2D* p, ZcmStereoPairPoint2D* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
