// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmStereoPairReconstruction.h"

static int __ZcmStereoPairReconstruction_hash_computed;
static uint64_t __ZcmStereoPairReconstruction_hash;

uint64_t __ZcmStereoPairReconstruction_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmStereoPairReconstruction_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmStereoPairReconstruction_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x440ea1890c9d4121LL
         + __ZcmService_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __ZcmStereoPairPoint3D_hash_recursive(&cp)
         + __ZcmCameraBaslerJpegFrame_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmStereoPairReconstruction_get_hash(void)
{
    if (!__ZcmStereoPairReconstruction_hash_computed) {
        __ZcmStereoPairReconstruction_hash = (int64_t)__ZcmStereoPairReconstruction_hash_recursive(NULL);
        __ZcmStereoPairReconstruction_hash_computed = 1;
    }

    return __ZcmStereoPairReconstruction_hash;
}

int __ZcmStereoPairReconstruction_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmStereoPairReconstruction* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __ZcmService_encode_array(buf, offset + pos, maxlen - pos, &(p[element].service), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].count), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmStereoPairPoint3D_encode_array(buf, offset + pos, maxlen - pos, p[element].points, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmCameraBaslerJpegFrame_encode_array(buf, offset + pos, maxlen - pos, &(p[element].jpeg_frame), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmStereoPairReconstruction_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmStereoPairReconstruction* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmStereoPairReconstruction_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmStereoPairReconstruction_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmStereoPairReconstruction_encoded_array_size(const ZcmStereoPairReconstruction* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __ZcmService_encoded_array_size(&(p[element].service), 1);

        size += __int32_t_encoded_array_size(&(p[element].count), 1);

        size += __ZcmStereoPairPoint3D_encoded_array_size(p[element].points, p[element].count);

        size += __ZcmCameraBaslerJpegFrame_encoded_array_size(&(p[element].jpeg_frame), 1);

    }
    return size;
}

uint32_t ZcmStereoPairReconstruction_encoded_size(const ZcmStereoPairReconstruction* p)
{
    return 8 + __ZcmStereoPairReconstruction_encoded_array_size(p, 1);
}

uint32_t ZcmStereoPairReconstruction_struct_size(void)
{
    return sizeof(ZcmStereoPairReconstruction);
}

uint32_t ZcmStereoPairReconstruction_num_fields(void)
{
    return 4;
}

int ZcmStereoPairReconstruction_get_field(const ZcmStereoPairReconstruction* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmStereoPairReconstruction_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            /* ZcmService */
            f->name = "service";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmService";
            f->num_dim = 0;
            f->data = (void*) &p->service;
            return 0;
        }
        
        case 1: {
            f->name = "count";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->count;
            return 0;
        }
        
        case 2: {
            /* ZcmStereoPairPoint3D */
            f->name = "points";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmStereoPairPoint3D";
            f->num_dim = 1;
            f->dim_size[0] = p->count;
            f->dim_is_variable[0] = 1;
            f->data = (void*) &p->points;
            return 0;
        }
        
        case 3: {
            /* ZcmCameraBaslerJpegFrame */
            f->name = "jpeg_frame";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmCameraBaslerJpegFrame";
            f->num_dim = 0;
            f->data = (void*) &p->jpeg_frame;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmStereoPairReconstruction_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmStereoPairReconstruction_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmStereoPairReconstruction_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmStereoPairReconstruction_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmStereoPairReconstruction_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmStereoPairReconstruction_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmStereoPairReconstruction_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmStereoPairReconstruction_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmStereoPairReconstruction_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmStereoPairReconstruction_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmStereoPairReconstruction* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __ZcmService_decode_array(buf, offset + pos, maxlen - pos, &(p[element].service), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].count), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].points = (ZcmStereoPairPoint3D*) zcm_malloc(sizeof(ZcmStereoPairPoint3D) * p[element].count);
        thislen = __ZcmStereoPairPoint3D_decode_array(buf, offset + pos, maxlen - pos, p[element].points, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmCameraBaslerJpegFrame_decode_array(buf, offset + pos, maxlen - pos, &(p[element].jpeg_frame), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmStereoPairReconstruction_decode_array_cleanup(ZcmStereoPairReconstruction* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __ZcmService_decode_array_cleanup(&(p[element].service), 1);

        __int32_t_decode_array_cleanup(&(p[element].count), 1);

        __ZcmStereoPairPoint3D_decode_array_cleanup(p[element].points, p[element].count);
        if (p[element].points) free(p[element].points);

        __ZcmCameraBaslerJpegFrame_decode_array_cleanup(&(p[element].jpeg_frame), 1);

    }
    return 0;
}

int ZcmStereoPairReconstruction_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmStereoPairReconstruction* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmStereoPairReconstruction_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmStereoPairReconstruction_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmStereoPairReconstruction_decode_cleanup(ZcmStereoPairReconstruction* p)
{
    return __ZcmStereoPairReconstruction_decode_array_cleanup(p, 1);
}

uint32_t __ZcmStereoPairReconstruction_clone_array(const ZcmStereoPairReconstruction* p, ZcmStereoPairReconstruction* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __ZcmService_clone_array(&(p[element].service), &(q[element].service), 1);

        n += __int32_t_clone_array(&(p[element].count), &(q[element].count), 1);

        q[element].points = (ZcmStereoPairPoint3D*) zcm_malloc(sizeof(ZcmStereoPairPoint3D) * q[element].count);
        n += __ZcmStereoPairPoint3D_clone_array(p[element].points, q[element].points, p[element].count);

        n += __ZcmCameraBaslerJpegFrame_clone_array(&(p[element].jpeg_frame), &(q[element].jpeg_frame), 1);

    }
    return n;
}

ZcmStereoPairReconstruction* ZcmStereoPairReconstruction_copy(const ZcmStereoPairReconstruction* p)
{
    ZcmStereoPairReconstruction* q = (ZcmStereoPairReconstruction*) malloc(sizeof(ZcmStereoPairReconstruction));
    __ZcmStereoPairReconstruction_clone_array(p, q, 1);
    return q;
}

void ZcmStereoPairReconstruction_destroy(ZcmStereoPairReconstruction* p)
{
    __ZcmStereoPairReconstruction_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmStereoPairReconstruction_publish(zcm_t* zcm, const char* channel, const ZcmStereoPairReconstruction* p)
{
      uint32_t max_data_size = ZcmStereoPairReconstruction_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmStereoPairReconstruction_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmStereoPairReconstruction_subscription_t {
    ZcmStereoPairReconstruction_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmStereoPairReconstruction_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmStereoPairReconstruction p;
    memset(&p, 0, sizeof(ZcmStereoPairReconstruction));
    status = ZcmStereoPairReconstruction_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmStereoPairReconstruction!!!\n", status);
        return;
    }

    ZcmStereoPairReconstruction_subscription_t* h = (ZcmStereoPairReconstruction_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmStereoPairReconstruction_decode_cleanup (&p);
}

ZcmStereoPairReconstruction_subscription_t* ZcmStereoPairReconstruction_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmStereoPairReconstruction_handler_t f, void* userdata)
{
    ZcmStereoPairReconstruction_subscription_t* n = (ZcmStereoPairReconstruction_subscription_t*)
                       malloc(sizeof(ZcmStereoPairReconstruction_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmStereoPairReconstruction_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmStereoPairReconstruction ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmStereoPairReconstruction_unsubscribe(zcm_t* zcm, ZcmStereoPairReconstruction_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmStereoPairReconstruction_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

