"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ZcmClusterAttributes(object):
    __slots__ = ["obstacle_type", "zone", "label", "probability", "distance"]

    def __init__(self):
        self.obstacle_type = 0
        self.zone = 0
        self.label = ""
        self.probability = 0.0
        self.distance = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ZcmClusterAttributes._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.obstacle_type, self.zone))
        __label_encoded = self.label.encode('utf-8')
        buf.write(struct.pack('>I', len(__label_encoded)+1))
        buf.write(__label_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">dd", self.probability, self.distance))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ZcmClusterAttributes._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ZcmClusterAttributes._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ZcmClusterAttributes()
        self.obstacle_type, self.zone = struct.unpack(">bb", buf.read(2))
        __label_len = struct.unpack('>I', buf.read(4))[0]
        self.label = buf.read(__label_len)[:-1].decode('utf-8', 'replace')
        self.probability, self.distance = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ZcmClusterAttributes in parents: return 0
        tmphash = (0x5e937f69cd7db5f6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ZcmClusterAttributes._packed_fingerprint is None:
            ZcmClusterAttributes._packed_fingerprint = struct.pack(">Q", ZcmClusterAttributes._get_hash_recursive([]))
        return ZcmClusterAttributes._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

