/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmFusionPredictedObstacle_hpp__
#define __ZcmFusionPredictedObstacle_hpp__

#include <vector>
#include "ZcmService.hpp"
#include "ZcmFusionZonePredictedObstacle.hpp"


/**
 * @struct ZcmFusionPredictedObstacle
 * @brief Препятствия во всех зонах контроля
 * @var ZcmFusionPredictedObstacle::service
 * @brief - служебное сообщение
 * @var ZcmFusionPredictedObstacle::ZONE_RED
 * @brief - идентификатор "красной" зоны (габарит подвижного состава)
 * @var ZcmFusionPredictedObstacle::ZONE_YELLOW
 * @brief - идентификатор "желтой" зоны (зона повышенного внимания со снижением скорости)
 * @var ZcmFusionPredictedObstacle::ZONE_BROWN
 * @brief - идентификатор "коричневой" зоны (зона отслеживания объектов)
 * @var ZcmFusionPredictedObstacle::OBSTACLE_TYPE_UNKNOWN
 * @brief - класс объекта - неизвестный
 * @var ZcmFusionPredictedObstacle::OBSTACLE_TYPE_HUMAN
 * @brief - класс объекта - человек
 * @var ZcmFusionPredictedObstacle::OBSTACLE_TYPE_TRAFFIC_LIGHT
 * @brief - класс объекта - светофор
 * @var ZcmFusionPredictedObstacle::OBSTACLE_TYPE_CAR
 * @brief - класс объекта - вагон
 * @var ZcmFusionPredictedObstacle::obstacles_count
 * @brief - количество препятствий
 * @var ZcmFusionPredictedObstacle::obstacles
 * @brief - препятствия
 *
 */
class ZcmFusionPredictedObstacle
{
    public:
        ZcmService service;

        int8_t     obstacles_count;

        std::vector< ZcmFusionZonePredictedObstacle > obstacles;

    public:
        #if __cplusplus > 199711L /* if c++11 */
        static constexpr int8_t   ZONE_RED = 1;
        static constexpr int8_t   ZONE_YELLOW = 2;
        static constexpr int8_t   ZONE_BROWN = 3;
        static constexpr int8_t   OBSTACLE_TYPE_UNKNOWN = 0;
        static constexpr int8_t   OBSTACLE_TYPE_HUMAN = 1;
        static constexpr int8_t   OBSTACLE_TYPE_TRAFFIC_LIGHT = 2;
        static constexpr int8_t   OBSTACLE_TYPE_CAR = 3;
        #else
        static const     int8_t   ZONE_RED = 1;
        static const     int8_t   ZONE_YELLOW = 2;
        static const     int8_t   ZONE_BROWN = 3;
        static const     int8_t   OBSTACLE_TYPE_UNKNOWN = 0;
        static const     int8_t   OBSTACLE_TYPE_HUMAN = 1;
        static const     int8_t   OBSTACLE_TYPE_TRAFFIC_LIGHT = 2;
        static const     int8_t   OBSTACLE_TYPE_CAR = 3;
        #endif

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmFusionPredictedObstacle() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmFusionPredictedObstacle"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmFusionPredictedObstacle::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmFusionPredictedObstacle::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmFusionPredictedObstacle::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmFusionPredictedObstacle::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmFusionPredictedObstacle::getTypeName()
{
    return "ZcmFusionPredictedObstacle";
}

int ZcmFusionPredictedObstacle::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->obstacles_count, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    for (int a0 = 0; a0 < this->obstacles_count; ++a0) {
        thislen = this->obstacles[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    return pos;
}

int ZcmFusionPredictedObstacle::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->obstacles_count, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    this->obstacles.resize(this->obstacles_count);
    for (int a0 = 0; a0 < this->obstacles_count; ++a0) {
        thislen = this->obstacles[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    return pos;
}

uint32_t ZcmFusionPredictedObstacle::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->service._getEncodedSizeNoHash();
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->obstacles_count; ++a0) {
        enc_size += this->obstacles[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

uint64_t ZcmFusionPredictedObstacle::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ZcmFusionPredictedObstacle::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)ZcmFusionPredictedObstacle::getHash };

    uint64_t hash = (uint64_t)0x9d14204a56ec6ebcLL +
         ZcmService::_computeHash(&cp) +
         ZcmFusionZonePredictedObstacle::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
