// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmVelocityVector.h"

static int __ZcmVelocityVector_hash_computed;
static uint64_t __ZcmVelocityVector_hash;

uint64_t __ZcmVelocityVector_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmVelocityVector_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmVelocityVector_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xff81898e62c543d3LL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmVelocityVector_get_hash(void)
{
    if (!__ZcmVelocityVector_hash_computed) {
        __ZcmVelocityVector_hash = (int64_t)__ZcmVelocityVector_hash_recursive(NULL);
        __ZcmVelocityVector_hash_computed = 1;
    }

    return __ZcmVelocityVector_hash;
}

int __ZcmVelocityVector_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmVelocityVector* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].vx), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].vy), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmVelocityVector_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmVelocityVector* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmVelocityVector_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmVelocityVector_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmVelocityVector_encoded_array_size(const ZcmVelocityVector* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __double_encoded_array_size(&(p[element].vx), 1);

        size += __double_encoded_array_size(&(p[element].vy), 1);

    }
    return size;
}

uint32_t ZcmVelocityVector_encoded_size(const ZcmVelocityVector* p)
{
    return 8 + __ZcmVelocityVector_encoded_array_size(p, 1);
}

uint32_t ZcmVelocityVector_struct_size(void)
{
    return sizeof(ZcmVelocityVector);
}

uint32_t ZcmVelocityVector_num_fields(void)
{
    return 2;
}

int ZcmVelocityVector_get_field(const ZcmVelocityVector* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmVelocityVector_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "vx";
            f->type = ZCM_FIELD_DOUBLE;
            f->typestr = "double";
            f->num_dim = 0;
            f->data = (void*) &p->vx;
            return 0;
        }
        
        case 1: {
            f->name = "vy";
            f->type = ZCM_FIELD_DOUBLE;
            f->typestr = "double";
            f->num_dim = 0;
            f->data = (void*) &p->vy;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmVelocityVector_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmVelocityVector_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmVelocityVector_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmVelocityVector_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmVelocityVector_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmVelocityVector_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmVelocityVector_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmVelocityVector_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmVelocityVector_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmVelocityVector_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmVelocityVector* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].vx), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].vy), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmVelocityVector_decode_array_cleanup(ZcmVelocityVector* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __double_decode_array_cleanup(&(p[element].vx), 1);

        __double_decode_array_cleanup(&(p[element].vy), 1);

    }
    return 0;
}

int ZcmVelocityVector_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmVelocityVector* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmVelocityVector_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmVelocityVector_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmVelocityVector_decode_cleanup(ZcmVelocityVector* p)
{
    return __ZcmVelocityVector_decode_array_cleanup(p, 1);
}

uint32_t __ZcmVelocityVector_clone_array(const ZcmVelocityVector* p, ZcmVelocityVector* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __double_clone_array(&(p[element].vx), &(q[element].vx), 1);

        n += __double_clone_array(&(p[element].vy), &(q[element].vy), 1);

    }
    return n;
}

ZcmVelocityVector* ZcmVelocityVector_copy(const ZcmVelocityVector* p)
{
    ZcmVelocityVector* q = (ZcmVelocityVector*) malloc(sizeof(ZcmVelocityVector));
    __ZcmVelocityVector_clone_array(p, q, 1);
    return q;
}

void ZcmVelocityVector_destroy(ZcmVelocityVector* p)
{
    __ZcmVelocityVector_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmVelocityVector_publish(zcm_t* zcm, const char* channel, const ZcmVelocityVector* p)
{
      uint32_t max_data_size = ZcmVelocityVector_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmVelocityVector_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmVelocityVector_subscription_t {
    ZcmVelocityVector_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmVelocityVector_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmVelocityVector p;
    memset(&p, 0, sizeof(ZcmVelocityVector));
    status = ZcmVelocityVector_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmVelocityVector!!!\n", status);
        return;
    }

    ZcmVelocityVector_subscription_t* h = (ZcmVelocityVector_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmVelocityVector_decode_cleanup (&p);
}

ZcmVelocityVector_subscription_t* ZcmVelocityVector_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmVelocityVector_handler_t f, void* userdata)
{
    ZcmVelocityVector_subscription_t* n = (ZcmVelocityVector_subscription_t*)
                       malloc(sizeof(ZcmVelocityVector_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmVelocityVector_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmVelocityVector ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmVelocityVector_unsubscribe(zcm_t* zcm, ZcmVelocityVector_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmVelocityVector_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

