// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmLidarClusterMediumPoint.h"

static int __ZcmLidarClusterMediumPoint_hash_computed;
static uint64_t __ZcmLidarClusterMediumPoint_hash;

uint64_t __ZcmLidarClusterMediumPoint_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmLidarClusterMediumPoint_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmLidarClusterMediumPoint_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x97333d4f21b591d0LL
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmLidarClusterMediumPoint_get_hash(void)
{
    if (!__ZcmLidarClusterMediumPoint_hash_computed) {
        __ZcmLidarClusterMediumPoint_hash = (int64_t)__ZcmLidarClusterMediumPoint_hash_recursive(NULL);
        __ZcmLidarClusterMediumPoint_hash_computed = 1;
    }

    return __ZcmLidarClusterMediumPoint_hash;
}

int __ZcmLidarClusterMediumPoint_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmLidarClusterMediumPoint* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].predicted_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].predicted_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].predicted_z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].corrected_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].corrected_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].corrected_z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmLidarClusterMediumPoint_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmLidarClusterMediumPoint* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmLidarClusterMediumPoint_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmLidarClusterMediumPoint_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmLidarClusterMediumPoint_encoded_array_size(const ZcmLidarClusterMediumPoint* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __float_encoded_array_size(&(p[element].x), 1);

        size += __float_encoded_array_size(&(p[element].y), 1);

        size += __float_encoded_array_size(&(p[element].z), 1);

        size += __float_encoded_array_size(&(p[element].predicted_x), 1);

        size += __float_encoded_array_size(&(p[element].predicted_y), 1);

        size += __float_encoded_array_size(&(p[element].predicted_z), 1);

        size += __float_encoded_array_size(&(p[element].corrected_x), 1);

        size += __float_encoded_array_size(&(p[element].corrected_y), 1);

        size += __float_encoded_array_size(&(p[element].corrected_z), 1);

    }
    return size;
}

uint32_t ZcmLidarClusterMediumPoint_encoded_size(const ZcmLidarClusterMediumPoint* p)
{
    return 8 + __ZcmLidarClusterMediumPoint_encoded_array_size(p, 1);
}

uint32_t ZcmLidarClusterMediumPoint_struct_size(void)
{
    return sizeof(ZcmLidarClusterMediumPoint);
}

uint32_t ZcmLidarClusterMediumPoint_num_fields(void)
{
    return 9;
}

int ZcmLidarClusterMediumPoint_get_field(const ZcmLidarClusterMediumPoint* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmLidarClusterMediumPoint_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "x";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->x;
            return 0;
        }
        
        case 1: {
            f->name = "y";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->y;
            return 0;
        }
        
        case 2: {
            f->name = "z";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->z;
            return 0;
        }
        
        case 3: {
            f->name = "predicted_x";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->predicted_x;
            return 0;
        }
        
        case 4: {
            f->name = "predicted_y";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->predicted_y;
            return 0;
        }
        
        case 5: {
            f->name = "predicted_z";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->predicted_z;
            return 0;
        }
        
        case 6: {
            f->name = "corrected_x";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->corrected_x;
            return 0;
        }
        
        case 7: {
            f->name = "corrected_y";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->corrected_y;
            return 0;
        }
        
        case 8: {
            f->name = "corrected_z";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->corrected_z;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmLidarClusterMediumPoint_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmLidarClusterMediumPoint_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmLidarClusterMediumPoint_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmLidarClusterMediumPoint_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmLidarClusterMediumPoint_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmLidarClusterMediumPoint_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmLidarClusterMediumPoint_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmLidarClusterMediumPoint_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmLidarClusterMediumPoint_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmLidarClusterMediumPoint_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmLidarClusterMediumPoint* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].predicted_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].predicted_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].predicted_z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].corrected_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].corrected_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].corrected_z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmLidarClusterMediumPoint_decode_array_cleanup(ZcmLidarClusterMediumPoint* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __float_decode_array_cleanup(&(p[element].x), 1);

        __float_decode_array_cleanup(&(p[element].y), 1);

        __float_decode_array_cleanup(&(p[element].z), 1);

        __float_decode_array_cleanup(&(p[element].predicted_x), 1);

        __float_decode_array_cleanup(&(p[element].predicted_y), 1);

        __float_decode_array_cleanup(&(p[element].predicted_z), 1);

        __float_decode_array_cleanup(&(p[element].corrected_x), 1);

        __float_decode_array_cleanup(&(p[element].corrected_y), 1);

        __float_decode_array_cleanup(&(p[element].corrected_z), 1);

    }
    return 0;
}

int ZcmLidarClusterMediumPoint_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmLidarClusterMediumPoint* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmLidarClusterMediumPoint_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmLidarClusterMediumPoint_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmLidarClusterMediumPoint_decode_cleanup(ZcmLidarClusterMediumPoint* p)
{
    return __ZcmLidarClusterMediumPoint_decode_array_cleanup(p, 1);
}

uint32_t __ZcmLidarClusterMediumPoint_clone_array(const ZcmLidarClusterMediumPoint* p, ZcmLidarClusterMediumPoint* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __float_clone_array(&(p[element].x), &(q[element].x), 1);

        n += __float_clone_array(&(p[element].y), &(q[element].y), 1);

        n += __float_clone_array(&(p[element].z), &(q[element].z), 1);

        n += __float_clone_array(&(p[element].predicted_x), &(q[element].predicted_x), 1);

        n += __float_clone_array(&(p[element].predicted_y), &(q[element].predicted_y), 1);

        n += __float_clone_array(&(p[element].predicted_z), &(q[element].predicted_z), 1);

        n += __float_clone_array(&(p[element].corrected_x), &(q[element].corrected_x), 1);

        n += __float_clone_array(&(p[element].corrected_y), &(q[element].corrected_y), 1);

        n += __float_clone_array(&(p[element].corrected_z), &(q[element].corrected_z), 1);

    }
    return n;
}

ZcmLidarClusterMediumPoint* ZcmLidarClusterMediumPoint_copy(const ZcmLidarClusterMediumPoint* p)
{
    ZcmLidarClusterMediumPoint* q = (ZcmLidarClusterMediumPoint*) malloc(sizeof(ZcmLidarClusterMediumPoint));
    __ZcmLidarClusterMediumPoint_clone_array(p, q, 1);
    return q;
}

void ZcmLidarClusterMediumPoint_destroy(ZcmLidarClusterMediumPoint* p)
{
    __ZcmLidarClusterMediumPoint_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmLidarClusterMediumPoint_publish(zcm_t* zcm, const char* channel, const ZcmLidarClusterMediumPoint* p)
{
      uint32_t max_data_size = ZcmLidarClusterMediumPoint_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmLidarClusterMediumPoint_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmLidarClusterMediumPoint_subscription_t {
    ZcmLidarClusterMediumPoint_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmLidarClusterMediumPoint_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmLidarClusterMediumPoint p;
    memset(&p, 0, sizeof(ZcmLidarClusterMediumPoint));
    status = ZcmLidarClusterMediumPoint_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmLidarClusterMediumPoint!!!\n", status);
        return;
    }

    ZcmLidarClusterMediumPoint_subscription_t* h = (ZcmLidarClusterMediumPoint_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmLidarClusterMediumPoint_decode_cleanup (&p);
}

ZcmLidarClusterMediumPoint_subscription_t* ZcmLidarClusterMediumPoint_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmLidarClusterMediumPoint_handler_t f, void* userdata)
{
    ZcmLidarClusterMediumPoint_subscription_t* n = (ZcmLidarClusterMediumPoint_subscription_t*)
                       malloc(sizeof(ZcmLidarClusterMediumPoint_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmLidarClusterMediumPoint_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmLidarClusterMediumPoint ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmLidarClusterMediumPoint_unsubscribe(zcm_t* zcm, ZcmLidarClusterMediumPoint_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmLidarClusterMediumPoint_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

