// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmLidarScalaUnfilteredObjectAttributes.h"

static int __ZcmLidarScalaUnfilteredObjectAttributes_hash_computed;
static uint64_t __ZcmLidarScalaUnfilteredObjectAttributes_hash;

uint64_t __ZcmLidarScalaUnfilteredObjectAttributes_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmLidarScalaUnfilteredObjectAttributes_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmLidarScalaUnfilteredObjectAttributes_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xcd5ea924fe640766LL
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __ZcmLidarScalaContourPoint_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmLidarScalaUnfilteredObjectAttributes_get_hash(void)
{
    if (!__ZcmLidarScalaUnfilteredObjectAttributes_hash_computed) {
        __ZcmLidarScalaUnfilteredObjectAttributes_hash = (int64_t)__ZcmLidarScalaUnfilteredObjectAttributes_hash_recursive(NULL);
        __ZcmLidarScalaUnfilteredObjectAttributes_hash_computed = 1;
    }

    return __ZcmLidarScalaUnfilteredObjectAttributes_hash;
}

int __ZcmLidarScalaUnfilteredObjectAttributes_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmLidarScalaUnfilteredObjectAttributes* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].relativeTimeOfMeasure), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].positionClosestObjectPointX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].positionClosestObjectPointY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeSigmaX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeSigmaY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxOrientation), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxOrientationSigma), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxHeight), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointLocation), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointCoordX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointCoordY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointCoordSigmaX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointCoordSigmaY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointPositionCorrCoeff), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].existenceProbaility), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].possibleNbOfContourPoints), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __ZcmLidarScalaContourPoint_encode_array(buf, offset + pos, maxlen - pos, p[element].contourPoints, p[element].possibleNbOfContourPoints);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmLidarScalaUnfilteredObjectAttributes_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmLidarScalaUnfilteredObjectAttributes* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmLidarScalaUnfilteredObjectAttributes_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmLidarScalaUnfilteredObjectAttributes_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmLidarScalaUnfilteredObjectAttributes_encoded_array_size(const ZcmLidarScalaUnfilteredObjectAttributes* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __int32_t_encoded_array_size(&(p[element].relativeTimeOfMeasure), 1);

        size += __float_encoded_array_size(&(p[element].positionClosestObjectPointX), 1);

        size += __float_encoded_array_size(&(p[element].positionClosestObjectPointY), 1);

        size += __float_encoded_array_size(&(p[element].objectBoxSizeX), 1);

        size += __float_encoded_array_size(&(p[element].objectBoxSizeY), 1);

        size += __float_encoded_array_size(&(p[element].objectBoxSizeSigmaX), 1);

        size += __float_encoded_array_size(&(p[element].objectBoxSizeSigmaY), 1);

        size += __float_encoded_array_size(&(p[element].objectBoxOrientation), 1);

        size += __float_encoded_array_size(&(p[element].objectBoxOrientationSigma), 1);

        size += __float_encoded_array_size(&(p[element].objectBoxHeight), 1);

        size += __int16_t_encoded_array_size(&(p[element].referencePointLocation), 1);

        size += __float_encoded_array_size(&(p[element].referencePointCoordX), 1);

        size += __float_encoded_array_size(&(p[element].referencePointCoordY), 1);

        size += __float_encoded_array_size(&(p[element].referencePointCoordSigmaX), 1);

        size += __float_encoded_array_size(&(p[element].referencePointCoordSigmaY), 1);

        size += __int16_t_encoded_array_size(&(p[element].referencePointPositionCorrCoeff), 1);

        size += __float_encoded_array_size(&(p[element].existenceProbaility), 1);

        size += __int16_t_encoded_array_size(&(p[element].possibleNbOfContourPoints), 1);

        size += __ZcmLidarScalaContourPoint_encoded_array_size(p[element].contourPoints, p[element].possibleNbOfContourPoints);

    }
    return size;
}

uint32_t ZcmLidarScalaUnfilteredObjectAttributes_encoded_size(const ZcmLidarScalaUnfilteredObjectAttributes* p)
{
    return 8 + __ZcmLidarScalaUnfilteredObjectAttributes_encoded_array_size(p, 1);
}

uint32_t ZcmLidarScalaUnfilteredObjectAttributes_struct_size(void)
{
    return sizeof(ZcmLidarScalaUnfilteredObjectAttributes);
}

uint32_t ZcmLidarScalaUnfilteredObjectAttributes_num_fields(void)
{
    return 19;
}

int ZcmLidarScalaUnfilteredObjectAttributes_get_field(const ZcmLidarScalaUnfilteredObjectAttributes* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmLidarScalaUnfilteredObjectAttributes_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "relativeTimeOfMeasure";
            f->type = ZCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void*) &p->relativeTimeOfMeasure;
            return 0;
        }
        
        case 1: {
            f->name = "positionClosestObjectPointX";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->positionClosestObjectPointX;
            return 0;
        }
        
        case 2: {
            f->name = "positionClosestObjectPointY";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->positionClosestObjectPointY;
            return 0;
        }
        
        case 3: {
            f->name = "objectBoxSizeX";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->objectBoxSizeX;
            return 0;
        }
        
        case 4: {
            f->name = "objectBoxSizeY";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->objectBoxSizeY;
            return 0;
        }
        
        case 5: {
            f->name = "objectBoxSizeSigmaX";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->objectBoxSizeSigmaX;
            return 0;
        }
        
        case 6: {
            f->name = "objectBoxSizeSigmaY";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->objectBoxSizeSigmaY;
            return 0;
        }
        
        case 7: {
            f->name = "objectBoxOrientation";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->objectBoxOrientation;
            return 0;
        }
        
        case 8: {
            f->name = "objectBoxOrientationSigma";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->objectBoxOrientationSigma;
            return 0;
        }
        
        case 9: {
            f->name = "objectBoxHeight";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->objectBoxHeight;
            return 0;
        }
        
        case 10: {
            f->name = "referencePointLocation";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->referencePointLocation;
            return 0;
        }
        
        case 11: {
            f->name = "referencePointCoordX";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->referencePointCoordX;
            return 0;
        }
        
        case 12: {
            f->name = "referencePointCoordY";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->referencePointCoordY;
            return 0;
        }
        
        case 13: {
            f->name = "referencePointCoordSigmaX";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->referencePointCoordSigmaX;
            return 0;
        }
        
        case 14: {
            f->name = "referencePointCoordSigmaY";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->referencePointCoordSigmaY;
            return 0;
        }
        
        case 15: {
            f->name = "referencePointPositionCorrCoeff";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->referencePointPositionCorrCoeff;
            return 0;
        }
        
        case 16: {
            f->name = "existenceProbaility";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void*) &p->existenceProbaility;
            return 0;
        }
        
        case 17: {
            f->name = "possibleNbOfContourPoints";
            f->type = ZCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void*) &p->possibleNbOfContourPoints;
            return 0;
        }
        
        case 18: {
            /* ZcmLidarScalaContourPoint */
            f->name = "contourPoints";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmLidarScalaContourPoint";
            f->num_dim = 1;
            f->dim_size[0] = p->possibleNbOfContourPoints;
            f->dim_is_variable[0] = 1;
            f->data = (void*) &p->contourPoints;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmLidarScalaUnfilteredObjectAttributes_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmLidarScalaUnfilteredObjectAttributes_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmLidarScalaUnfilteredObjectAttributes_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmLidarScalaUnfilteredObjectAttributes_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmLidarScalaUnfilteredObjectAttributes_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmLidarScalaUnfilteredObjectAttributes_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmLidarScalaUnfilteredObjectAttributes_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmLidarScalaUnfilteredObjectAttributes_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmLidarScalaUnfilteredObjectAttributes_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmLidarScalaUnfilteredObjectAttributes_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmLidarScalaUnfilteredObjectAttributes* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].relativeTimeOfMeasure), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].positionClosestObjectPointX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].positionClosestObjectPointY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeSigmaX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxSizeSigmaY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxOrientation), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxOrientationSigma), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].objectBoxHeight), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointLocation), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointCoordX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointCoordY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointCoordSigmaX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointCoordSigmaY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].referencePointPositionCorrCoeff), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].existenceProbaility), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].possibleNbOfContourPoints), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].contourPoints = (ZcmLidarScalaContourPoint*) zcm_malloc(sizeof(ZcmLidarScalaContourPoint) * p[element].possibleNbOfContourPoints);
        thislen = __ZcmLidarScalaContourPoint_decode_array(buf, offset + pos, maxlen - pos, p[element].contourPoints, p[element].possibleNbOfContourPoints);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmLidarScalaUnfilteredObjectAttributes_decode_array_cleanup(ZcmLidarScalaUnfilteredObjectAttributes* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __int32_t_decode_array_cleanup(&(p[element].relativeTimeOfMeasure), 1);

        __float_decode_array_cleanup(&(p[element].positionClosestObjectPointX), 1);

        __float_decode_array_cleanup(&(p[element].positionClosestObjectPointY), 1);

        __float_decode_array_cleanup(&(p[element].objectBoxSizeX), 1);

        __float_decode_array_cleanup(&(p[element].objectBoxSizeY), 1);

        __float_decode_array_cleanup(&(p[element].objectBoxSizeSigmaX), 1);

        __float_decode_array_cleanup(&(p[element].objectBoxSizeSigmaY), 1);

        __float_decode_array_cleanup(&(p[element].objectBoxOrientation), 1);

        __float_decode_array_cleanup(&(p[element].objectBoxOrientationSigma), 1);

        __float_decode_array_cleanup(&(p[element].objectBoxHeight), 1);

        __int16_t_decode_array_cleanup(&(p[element].referencePointLocation), 1);

        __float_decode_array_cleanup(&(p[element].referencePointCoordX), 1);

        __float_decode_array_cleanup(&(p[element].referencePointCoordY), 1);

        __float_decode_array_cleanup(&(p[element].referencePointCoordSigmaX), 1);

        __float_decode_array_cleanup(&(p[element].referencePointCoordSigmaY), 1);

        __int16_t_decode_array_cleanup(&(p[element].referencePointPositionCorrCoeff), 1);

        __float_decode_array_cleanup(&(p[element].existenceProbaility), 1);

        __int16_t_decode_array_cleanup(&(p[element].possibleNbOfContourPoints), 1);

        __ZcmLidarScalaContourPoint_decode_array_cleanup(p[element].contourPoints, p[element].possibleNbOfContourPoints);
        if (p[element].contourPoints) free(p[element].contourPoints);

    }
    return 0;
}

int ZcmLidarScalaUnfilteredObjectAttributes_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmLidarScalaUnfilteredObjectAttributes* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmLidarScalaUnfilteredObjectAttributes_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmLidarScalaUnfilteredObjectAttributes_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmLidarScalaUnfilteredObjectAttributes_decode_cleanup(ZcmLidarScalaUnfilteredObjectAttributes* p)
{
    return __ZcmLidarScalaUnfilteredObjectAttributes_decode_array_cleanup(p, 1);
}

uint32_t __ZcmLidarScalaUnfilteredObjectAttributes_clone_array(const ZcmLidarScalaUnfilteredObjectAttributes* p, ZcmLidarScalaUnfilteredObjectAttributes* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __int32_t_clone_array(&(p[element].relativeTimeOfMeasure), &(q[element].relativeTimeOfMeasure), 1);

        n += __float_clone_array(&(p[element].positionClosestObjectPointX), &(q[element].positionClosestObjectPointX), 1);

        n += __float_clone_array(&(p[element].positionClosestObjectPointY), &(q[element].positionClosestObjectPointY), 1);

        n += __float_clone_array(&(p[element].objectBoxSizeX), &(q[element].objectBoxSizeX), 1);

        n += __float_clone_array(&(p[element].objectBoxSizeY), &(q[element].objectBoxSizeY), 1);

        n += __float_clone_array(&(p[element].objectBoxSizeSigmaX), &(q[element].objectBoxSizeSigmaX), 1);

        n += __float_clone_array(&(p[element].objectBoxSizeSigmaY), &(q[element].objectBoxSizeSigmaY), 1);

        n += __float_clone_array(&(p[element].objectBoxOrientation), &(q[element].objectBoxOrientation), 1);

        n += __float_clone_array(&(p[element].objectBoxOrientationSigma), &(q[element].objectBoxOrientationSigma), 1);

        n += __float_clone_array(&(p[element].objectBoxHeight), &(q[element].objectBoxHeight), 1);

        n += __int16_t_clone_array(&(p[element].referencePointLocation), &(q[element].referencePointLocation), 1);

        n += __float_clone_array(&(p[element].referencePointCoordX), &(q[element].referencePointCoordX), 1);

        n += __float_clone_array(&(p[element].referencePointCoordY), &(q[element].referencePointCoordY), 1);

        n += __float_clone_array(&(p[element].referencePointCoordSigmaX), &(q[element].referencePointCoordSigmaX), 1);

        n += __float_clone_array(&(p[element].referencePointCoordSigmaY), &(q[element].referencePointCoordSigmaY), 1);

        n += __int16_t_clone_array(&(p[element].referencePointPositionCorrCoeff), &(q[element].referencePointPositionCorrCoeff), 1);

        n += __float_clone_array(&(p[element].existenceProbaility), &(q[element].existenceProbaility), 1);

        n += __int16_t_clone_array(&(p[element].possibleNbOfContourPoints), &(q[element].possibleNbOfContourPoints), 1);

        q[element].contourPoints = (ZcmLidarScalaContourPoint*) zcm_malloc(sizeof(ZcmLidarScalaContourPoint) * q[element].possibleNbOfContourPoints);
        n += __ZcmLidarScalaContourPoint_clone_array(p[element].contourPoints, q[element].contourPoints, p[element].possibleNbOfContourPoints);

    }
    return n;
}

ZcmLidarScalaUnfilteredObjectAttributes* ZcmLidarScalaUnfilteredObjectAttributes_copy(const ZcmLidarScalaUnfilteredObjectAttributes* p)
{
    ZcmLidarScalaUnfilteredObjectAttributes* q = (ZcmLidarScalaUnfilteredObjectAttributes*) malloc(sizeof(ZcmLidarScalaUnfilteredObjectAttributes));
    __ZcmLidarScalaUnfilteredObjectAttributes_clone_array(p, q, 1);
    return q;
}

void ZcmLidarScalaUnfilteredObjectAttributes_destroy(ZcmLidarScalaUnfilteredObjectAttributes* p)
{
    __ZcmLidarScalaUnfilteredObjectAttributes_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmLidarScalaUnfilteredObjectAttributes_publish(zcm_t* zcm, const char* channel, const ZcmLidarScalaUnfilteredObjectAttributes* p)
{
      uint32_t max_data_size = ZcmLidarScalaUnfilteredObjectAttributes_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmLidarScalaUnfilteredObjectAttributes_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmLidarScalaUnfilteredObjectAttributes_subscription_t {
    ZcmLidarScalaUnfilteredObjectAttributes_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmLidarScalaUnfilteredObjectAttributes_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmLidarScalaUnfilteredObjectAttributes p;
    memset(&p, 0, sizeof(ZcmLidarScalaUnfilteredObjectAttributes));
    status = ZcmLidarScalaUnfilteredObjectAttributes_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmLidarScalaUnfilteredObjectAttributes!!!\n", status);
        return;
    }

    ZcmLidarScalaUnfilteredObjectAttributes_subscription_t* h = (ZcmLidarScalaUnfilteredObjectAttributes_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmLidarScalaUnfilteredObjectAttributes_decode_cleanup (&p);
}

ZcmLidarScalaUnfilteredObjectAttributes_subscription_t* ZcmLidarScalaUnfilteredObjectAttributes_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmLidarScalaUnfilteredObjectAttributes_handler_t f, void* userdata)
{
    ZcmLidarScalaUnfilteredObjectAttributes_subscription_t* n = (ZcmLidarScalaUnfilteredObjectAttributes_subscription_t*)
                       malloc(sizeof(ZcmLidarScalaUnfilteredObjectAttributes_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmLidarScalaUnfilteredObjectAttributes_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmLidarScalaUnfilteredObjectAttributes ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmLidarScalaUnfilteredObjectAttributes_unsubscribe(zcm_t* zcm, ZcmLidarScalaUnfilteredObjectAttributes_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmLidarScalaUnfilteredObjectAttributes_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

