"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ZcmObstacleDetectorPoint2D(object):
    __slots__ = ["x", "y"]

    def __init__(self):
        self.x = 0.0
        self.y = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ZcmObstacleDetectorPoint2D._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dd", self.x, self.y))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ZcmObstacleDetectorPoint2D._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ZcmObstacleDetectorPoint2D._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ZcmObstacleDetectorPoint2D()
        self.x, self.y = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ZcmObstacleDetectorPoint2D in parents: return 0
        tmphash = (0xc393874307e7ecbc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ZcmObstacleDetectorPoint2D._packed_fingerprint is None:
            ZcmObstacleDetectorPoint2D._packed_fingerprint = struct.pack(">Q", ZcmObstacleDetectorPoint2D._get_hash_recursive([]))
        return ZcmObstacleDetectorPoint2D._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

