// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#include "ZcmHomography.h"

static int __ZcmHomography_hash_computed;
static uint64_t __ZcmHomography_hash;

uint64_t __ZcmHomography_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ZcmHomography_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ZcmHomography_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x19b67da422fbe756LL
         + __ZcmService_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ZcmHomography_get_hash(void)
{
    if (!__ZcmHomography_hash_computed) {
        __ZcmHomography_hash = (int64_t)__ZcmHomography_hash_recursive(NULL);
        __ZcmHomography_hash_computed = 1;
    }

    return __ZcmHomography_hash;
}

int __ZcmHomography_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const ZcmHomography* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __ZcmService_encode_array(buf, offset + pos, maxlen - pos, &(p[element].service), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].rotation, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].translation, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].normal, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ZcmHomography_encode(void* buf, uint32_t offset, uint32_t maxlen, const ZcmHomography* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmHomography_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ZcmHomography_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __ZcmHomography_encoded_array_size(const ZcmHomography* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __ZcmService_encoded_array_size(&(p[element].service), 1);

        size += __float_encoded_array_size(p[element].rotation, 3);

        size += __float_encoded_array_size(p[element].translation, 3);

        size += __float_encoded_array_size(p[element].normal, 3);

    }
    return size;
}

uint32_t ZcmHomography_encoded_size(const ZcmHomography* p)
{
    return 8 + __ZcmHomography_encoded_array_size(p, 1);
}

uint32_t ZcmHomography_struct_size(void)
{
    return sizeof(ZcmHomography);
}

uint32_t ZcmHomography_num_fields(void)
{
    return 4;
}

int ZcmHomography_get_field(const ZcmHomography* p, uint32_t i, zcm_field_t* f)
{
    if (i >= ZcmHomography_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            /* ZcmService */
            f->name = "service";
            f->type = ZCM_FIELD_USER_TYPE;
            f->typestr = "ZcmService";
            f->num_dim = 0;
            f->data = (void*) &p->service;
            return 0;
        }
        
        case 1: {
            f->name = "rotation";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 1;
            f->dim_size[0] = 3;
            f->dim_is_variable[0] = 0;
            f->data = (void*) &p->rotation;
            return 0;
        }
        
        case 2: {
            f->name = "translation";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 1;
            f->dim_size[0] = 3;
            f->dim_is_variable[0] = 0;
            f->data = (void*) &p->translation;
            return 0;
        }
        
        case 3: {
            f->name = "normal";
            f->type = ZCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 1;
            f->dim_size[0] = 3;
            f->dim_is_variable[0] = 0;
            f->data = (void*) &p->normal;
            return 0;
        }
        
        default:
            return 1;
    }
}

const zcm_type_info_t* ZcmHomography_get_type_info(void)
{
    static int init = 0;
    static zcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (zcm_encode_t) ZcmHomography_encode;
        typeinfo.decode         = (zcm_decode_t) ZcmHomography_decode;
        typeinfo.decode_cleanup = (zcm_decode_cleanup_t) ZcmHomography_decode_cleanup;
        typeinfo.encoded_size   = (zcm_encoded_size_t) ZcmHomography_encoded_size;
        typeinfo.struct_size    = (zcm_struct_size_t)  ZcmHomography_struct_size;
        typeinfo.num_fields     = (zcm_num_fields_t) ZcmHomography_num_fields;
        typeinfo.get_field      = (zcm_get_field_t) ZcmHomography_get_field;
        typeinfo.get_hash       = (zcm_get_hash_t) __ZcmHomography_get_hash;
    }
    
    return &typeinfo;
}
int __ZcmHomography_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, ZcmHomography* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __ZcmService_decode_array(buf, offset + pos, maxlen - pos, &(p[element].service), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].rotation, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].translation, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].normal, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ZcmHomography_decode_array_cleanup(ZcmHomography* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __ZcmService_decode_array_cleanup(&(p[element].service), 1);

        __float_decode_array_cleanup(p[element].rotation, 3);

        __float_decode_array_cleanup(p[element].translation, 3);

        __float_decode_array_cleanup(p[element].normal, 3);

    }
    return 0;
}

int ZcmHomography_decode(const void* buf, uint32_t offset, uint32_t maxlen, ZcmHomography* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __ZcmHomography_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ZcmHomography_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmHomography_decode_cleanup(ZcmHomography* p)
{
    return __ZcmHomography_decode_array_cleanup(p, 1);
}

uint32_t __ZcmHomography_clone_array(const ZcmHomography* p, ZcmHomography* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __ZcmService_clone_array(&(p[element].service), &(q[element].service), 1);

        n += __float_clone_array(p[element].rotation, q[element].rotation, 3);

        n += __float_clone_array(p[element].translation, q[element].translation, 3);

        n += __float_clone_array(p[element].normal, q[element].normal, 3);

    }
    return n;
}

ZcmHomography* ZcmHomography_copy(const ZcmHomography* p)
{
    ZcmHomography* q = (ZcmHomography*) malloc(sizeof(ZcmHomography));
    __ZcmHomography_clone_array(p, q, 1);
    return q;
}

void ZcmHomography_destroy(ZcmHomography* p)
{
    __ZcmHomography_decode_array_cleanup(p, 1);
    free(p);
}

int ZcmHomography_publish(zcm_t* zcm, const char* channel, const ZcmHomography* p)
{
      uint32_t max_data_size = ZcmHomography_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ZcmHomography_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _ZcmHomography_subscription_t {
    ZcmHomography_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void ZcmHomography_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    ZcmHomography p;
    memset(&p, 0, sizeof(ZcmHomography));
    status = ZcmHomography_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ZcmHomography!!!\n", status);
        return;
    }

    ZcmHomography_subscription_t* h = (ZcmHomography_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ZcmHomography_decode_cleanup (&p);
}

ZcmHomography_subscription_t* ZcmHomography_subscribe (zcm_t* zcm,
                    const char* channel,
                    ZcmHomography_handler_t f, void* userdata)
{
    ZcmHomography_subscription_t* n = (ZcmHomography_subscription_t*)
                       malloc(sizeof(ZcmHomography_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              ZcmHomography_handler_stub, n);
    if (n->z_sub == NULL) {
        fprintf (stderr,"couldn't reg ZcmHomography ZCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ZcmHomography_unsubscribe(zcm_t* zcm, ZcmHomography_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ZcmHomography_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

