"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ZcmObstacleGeoCoordinates(object):
    __slots__ = ["lat", "lon"]

    def __init__(self):
        self.lat = 0.0
        self.lon = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ZcmObstacleGeoCoordinates._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dd", self.lat, self.lon))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ZcmObstacleGeoCoordinates._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ZcmObstacleGeoCoordinates._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ZcmObstacleGeoCoordinates()
        self.lat, self.lon = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ZcmObstacleGeoCoordinates in parents: return 0
        tmphash = (0x762ea685263685c1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ZcmObstacleGeoCoordinates._packed_fingerprint is None:
            ZcmObstacleGeoCoordinates._packed_fingerprint = struct.pack(">Q", ZcmObstacleGeoCoordinates._get_hash_recursive([]))
        return ZcmObstacleGeoCoordinates._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

