"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ZcmObstacleProperties(object):
    __slots__ = ["width", "length", "angle"]

    def __init__(self):
        self.width = 0.0
        self.length = 0.0
        self.angle = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ZcmObstacleProperties._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddd", self.width, self.length, self.angle))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ZcmObstacleProperties._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ZcmObstacleProperties._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ZcmObstacleProperties()
        self.width, self.length, self.angle = struct.unpack(">ddd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ZcmObstacleProperties in parents: return 0
        tmphash = (0x98f9449d3f585d1a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ZcmObstacleProperties._packed_fingerprint is None:
            ZcmObstacleProperties._packed_fingerprint = struct.pack(">Q", ZcmObstacleProperties._get_hash_recursive([]))
        return ZcmObstacleProperties._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

