"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from ZcmService import ZcmService

class ZcmRadarContiObjectListStatus(object):
    __slots__ = ["service", "number_objects", "meas_counter", "interface_version"]

    def __init__(self):
        self.service = ZcmService()
        self.number_objects = 0
        self.meas_counter = 0
        self.interface_version = 0

    def encode(self):
        buf = BytesIO()
        buf.write(ZcmRadarContiObjectListStatus._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.service._get_packed_fingerprint() == ZcmService._get_packed_fingerprint()
        self.service._encode_one(buf)
        buf.write(struct.pack(">hib", self.number_objects, self.meas_counter, self.interface_version))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ZcmRadarContiObjectListStatus._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ZcmRadarContiObjectListStatus._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ZcmRadarContiObjectListStatus()
        self.service = ZcmService._decode_one(buf)
        self.number_objects, self.meas_counter, self.interface_version = struct.unpack(">hib", buf.read(7))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ZcmRadarContiObjectListStatus in parents: return 0
        newparents = parents + [ZcmRadarContiObjectListStatus]
        tmphash = (0x38b7ee89addab6eb+ ZcmService._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ZcmRadarContiObjectListStatus._packed_fingerprint is None:
            ZcmRadarContiObjectListStatus._packed_fingerprint = struct.pack(">Q", ZcmRadarContiObjectListStatus._get_hash_recursive([]))
        return ZcmRadarContiObjectListStatus._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

