"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from ZcmService import ZcmService

class ZcmRadarContiClusterQualityInfo(object):
    __slots__ = ["service", "id", "dist_long_rms", "dist_lat_rms", "vrel_long_rms", "vrel_lat_rms", "pdh0", "invalid_state", "ambig_state"]

    def __init__(self):
        self.service = ZcmService()
        self.id = 0
        self.dist_long_rms = 0.0
        self.dist_lat_rms = 0.0
        self.vrel_long_rms = 0.0
        self.vrel_lat_rms = 0.0
        self.pdh0 = 0.0
        self.invalid_state = 0.0
        self.ambig_state = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ZcmRadarContiClusterQualityInfo._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.service._get_packed_fingerprint() == ZcmService._get_packed_fingerprint()
        self.service._encode_one(buf)
        buf.write(struct.pack(">hfffffff", self.id, self.dist_long_rms, self.dist_lat_rms, self.vrel_long_rms, self.vrel_lat_rms, self.pdh0, self.invalid_state, self.ambig_state))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ZcmRadarContiClusterQualityInfo._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ZcmRadarContiClusterQualityInfo._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ZcmRadarContiClusterQualityInfo()
        self.service = ZcmService._decode_one(buf)
        self.id, self.dist_long_rms, self.dist_lat_rms, self.vrel_long_rms, self.vrel_lat_rms, self.pdh0, self.invalid_state, self.ambig_state = struct.unpack(">hfffffff", buf.read(30))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ZcmRadarContiClusterQualityInfo in parents: return 0
        newparents = parents + [ZcmRadarContiClusterQualityInfo]
        tmphash = (0xad2c43b3b3d66cbb+ ZcmService._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ZcmRadarContiClusterQualityInfo._packed_fingerprint is None:
            ZcmRadarContiClusterQualityInfo._packed_fingerprint = struct.pack(">Q", ZcmRadarContiClusterQualityInfo._get_hash_recursive([]))
        return ZcmRadarContiClusterQualityInfo._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

