/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmMalsRoute_hpp__
#define __ZcmMalsRoute_hpp__

#include <vector>
#include <string>
#include "ZcmService.hpp"
#include "ZcmMalsSwitch.hpp"


/**
 * @struct ZcmMalsRoute
 * @brief информация от MAЛС о текущем пути
 * @var ZcmMalsRoute::count
 * @brief - количество стрелок
 *          
 * @var ZcmMalsRoute::switches  
 * @brief - массив стрелок
 *          
 * @var ZcmMalsRoute::current_section         
 * @brief - имя текущей секции занимаемой локомотивом
 * @var ZcmMalsRoute::border1/border2
 * @brief - начало/конец маршрута                  
 *
 */
class ZcmMalsRoute
{
    public:
        ZcmService service;

        int16_t    count;

        std::vector< ZcmMalsSwitch > switches;

        std::string current_section;

        std::string border1;

        std::string border2;

    public:
        #if __cplusplus > 199711L /* if c++11 */
        static constexpr int8_t   SWITCH_STATE_UNKNOWN = 0;
        static constexpr int8_t   SWITCH_STATE_PLUS = 1;
        static constexpr int8_t   SWITCH_STATE_MINUS = 2;
        #else
        static const     int8_t   SWITCH_STATE_UNKNOWN = 0;
        static const     int8_t   SWITCH_STATE_PLUS = 1;
        static const     int8_t   SWITCH_STATE_MINUS = 2;
        #endif

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmMalsRoute() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmMalsRoute"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmMalsRoute::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmMalsRoute::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmMalsRoute::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmMalsRoute::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmMalsRoute::getTypeName()
{
    return "ZcmMalsRoute";
}

int ZcmMalsRoute::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->count, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    for (int a0 = 0; a0 < this->count; ++a0) {
        thislen = this->switches[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    char* current_section_cstr = (char*) this->current_section.c_str();
    thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &current_section_cstr, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    char* border1_cstr = (char*) this->border1.c_str();
    thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &border1_cstr, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    char* border2_cstr = (char*) this->border2.c_str();
    thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &border2_cstr, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmMalsRoute::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->count, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    this->switches.resize(this->count);
    for (int a0 = 0; a0 < this->count; ++a0) {
        thislen = this->switches[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    int32_t __current_section_len__;
    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__current_section_len__, 1);
    if(thislen < 0) return thislen; else pos += thislen;
    if((uint32_t)__current_section_len__ > maxlen - pos) return -1;
    this->current_section.assign(((const char*)buf) + offset + pos, __current_section_len__ - 1);
    pos += __current_section_len__;

    int32_t __border1_len__;
    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__border1_len__, 1);
    if(thislen < 0) return thislen; else pos += thislen;
    if((uint32_t)__border1_len__ > maxlen - pos) return -1;
    this->border1.assign(((const char*)buf) + offset + pos, __border1_len__ - 1);
    pos += __border1_len__;

    int32_t __border2_len__;
    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__border2_len__, 1);
    if(thislen < 0) return thislen; else pos += thislen;
    if((uint32_t)__border2_len__ > maxlen - pos) return -1;
    this->border2.assign(((const char*)buf) + offset + pos, __border2_len__ - 1);
    pos += __border2_len__;

    return pos;
}

uint32_t ZcmMalsRoute::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->service._getEncodedSizeNoHash();
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->count; ++a0) {
        enc_size += this->switches[a0]._getEncodedSizeNoHash();
    }
    enc_size += this->current_section.size() + 4 + 1;
    enc_size += this->border1.size() + 4 + 1;
    enc_size += this->border2.size() + 4 + 1;
    return enc_size;
}

uint64_t ZcmMalsRoute::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ZcmMalsRoute::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)ZcmMalsRoute::getHash };

    uint64_t hash = (uint64_t)0xf2d4274b0fa6d7fdLL +
         ZcmService::_computeHash(&cp) +
         ZcmMalsSwitch::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
