/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmSauglDiagnostics_hpp__
#define __ZcmSauglDiagnostics_hpp__

#include "ZcmService.hpp"


/**
 * @struct ZcmSauglDiagnostics
 * @brief Диагностика САУ-ГЛ
 * @var ZcmSauglDiagnostics::power
 * @brief - Позиция контроллера машиниста в режиме тяги либо электро-динамического торможения (ЭДТ)
 * @var ZcmSauglDiagnostics::is_power_brake
 * @brief - Режим электро-динамического торможения (ЭДТ)
 * @var ZcmSauglDiagnostics::is_hold_speed
 * @brief - Поддержание скорости
 * @var ZcmSauglDiagnostics::is_reversor_forward
 * @brief - Фактическое положение реверсора - вперед
 * @var ZcmSauglDiagnostics::is_reversor_backward
 * @brief - Фактическое положение реверсора - назад
 * @var ZcmSauglDiagnostics::mode
 * @brief - Режим управления
 * @var ZcmSauglDiagnostics::hold_speed
 * @brief - Значение поддерживаемой скорости, 0.5 км/ч
 * @var ZcmSauglDiagnostics::speed
 * @brief - Фактическая скорость, 0.1 км/ч
 * @var ZcmSauglDiagnostics::MODE_DISTANT_CONTROL_OFF
 * @brief - Константа, режим управления - дистанционное управление не активно
 * @var ZcmSauglDiagnostics::MODE_DISTANT_CONTROL
 * @brief - Константа, режим управления - локомотив находится в режиме дистанционного управления
 *
 */
class ZcmSauglDiagnostics
{
    public:
        ZcmService service;

        int8_t     power;

        int8_t     is_power_brake;

        int8_t     is_hold_speed;

        int8_t     is_reversor_forward;

        int8_t     is_reversor_backward;

        int16_t    mode;

        int8_t     is_test_request;

        int16_t    hold_speed;

        int32_t    speed;

    public:
        #if __cplusplus > 199711L /* if c++11 */
        static constexpr int16_t  MODE_DISTANT_CONTROL_OFF = 0;
        static constexpr int16_t  MODE_DISTANT_CONTROL = 3;
        #else
        static const     int16_t  MODE_DISTANT_CONTROL_OFF = 0;
        static const     int16_t  MODE_DISTANT_CONTROL = 3;
        #endif

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmSauglDiagnostics() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmSauglDiagnostics"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmSauglDiagnostics::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmSauglDiagnostics::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmSauglDiagnostics::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmSauglDiagnostics::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmSauglDiagnostics::getTypeName()
{
    return "ZcmSauglDiagnostics";
}

int ZcmSauglDiagnostics::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->power, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->is_power_brake, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->is_hold_speed, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->is_reversor_forward, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->is_reversor_backward, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->mode, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->is_test_request, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->hold_speed, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->speed, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmSauglDiagnostics::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->power, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->is_power_brake, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->is_hold_speed, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->is_reversor_forward, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->is_reversor_backward, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->mode, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->is_test_request, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->hold_speed, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->speed, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmSauglDiagnostics::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->service._getEncodedSizeNoHash();
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t ZcmSauglDiagnostics::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ZcmSauglDiagnostics::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)ZcmSauglDiagnostics::getHash };

    uint64_t hash = (uint64_t)0x873ef9bafbc56b95LL +
         ZcmService::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
